// Package main generates Go settings structs from golangci-lint's JSON Schema.
//
// Usage:
//
//	go run ./cmd/generate-settings -schema=pkg/constants/schema/golangci-lint.jsonschema.json -output=pkg/constants/linter_settings_generated.go
//
// The generated structs implement SettingsConverter via a generated ToMap() method.
// The output file has a `//go:build generate` constraint so it does not participate
// in normal compilation — it exists as a reference for hand-maintaining the curated
// structs in linter_settings.go.
//
//nolint:all // dev tool — parses external JSON with lowercase schema keys
package main

import (
	"encoding/json/v2"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"
)

type schemaDef struct {
	Type        string               `json:"type"`
	Properties  map[string]schemaDef `json:"properties"`
	Items       *schemaDef           `json:"items"`
	Ref         string               `json:"$ref"`
	Description string               `json:"description"`
	Enum        []any                `json:"enum"`
}

type jsonSchema struct {
	Definitions struct {
		Settings struct {
			Definitions map[string]schemaDef `json:"definitions"`
		} `json:"settings"`
	} `json:"definitions"`
	Properties struct {
		Linters struct {
			Properties struct {
				Settings struct {
					Properties map[string]schemaDef `json:"properties"`
				} `json:"settings"`
			} `json:"properties"`
		} `json:"linters"`
	} `json:"properties"`
}

func main() {
	schemaPath := flag.String("schema", "", "path to golangci-lint JSON Schema")
	outputPath := flag.String("output", "", "path to output generated Go file")
	schemaVersion := flag.String("schema-version", "",
		"golangci-lint version the schema snapshot was taken from (e.g. v2.13.2)")
	minToolVersion := flag.String("min-tool-version", "v2.10.1",
		"minimum golangci-lint version the tool supports")

	flag.Parse()

	if *schemaPath == "" || *outputPath == "" {
		fmt.Fprintln(os.Stderr, "usage: generate-settings -schema=<path> -output=<path>")
		os.Exit(1)
	}

	if newer, ok := isNewerVersion(*schemaVersion, *minToolVersion); ok && newer {
		fmt.Fprintf(os.Stderr,
			"WARNING: schema snapshot %s is NEWER than the tool minimum %s.\n"+
				"Settings keys from the snapshot may not exist in older golangci-lint.\n"+
				"The curated defaults in pkg/constants/linter_settings.go are schema-verified\n"+
				"per CI (schema-verify job) - regenerate the fixture when bumping keys.\n",
			*schemaVersion, *minToolVersion)
	}

	data, err := os.ReadFile(*schemaPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read schema: %v\n", err)
		os.Exit(1)
	}

	var schema jsonSchema
	if err := json.Unmarshal(data, &schema); err != nil {
		fmt.Fprintf(os.Stderr, "parse schema: %v\n", err)
		os.Exit(1)
	}

	settingsDefs := schema.Definitions.Settings.Definitions
	linterSettingsProps := schema.Properties.Linters.Properties.Settings.Properties

	var b strings.Builder
	b.WriteString("// Code generated by go run ./cmd/generate-settings. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Schema provenance:\n")
	b.WriteString(fmt.Sprintf("//   Schema snapshot: %s\n", orUnknown(*schemaVersion)))
	b.WriteString(fmt.Sprintf("//   Tool minimum:   %s (pkg/constants.MinGolangCILintVersion)\n", *minToolVersion))
	b.WriteString("//\n")
	b.WriteString("// A schema snapshot NEWER than the tool minimum may contain keys that do\n")
	b.WriteString("// not exist in older golangci-lint. The curated structs in\n")
	b.WriteString("// linter_settings.go (the compiled truth) are schema-verified by the CI\n")
	b.WriteString("// schema-verify job against the pinned golangci-lint version.\n")
	b.WriteString("//go:build generate\n\n")
	b.WriteString("package constants\n\n")
	b.WriteString("import \"github.com/larsartmann/golangci-lint-auto-configure/pkg/types\"\n\n")

	linterNames := make([]string, 0, len(linterSettingsProps))
	for name := range linterSettingsProps {
		linterNames = append(linterNames, name)
	}

	sort.Strings(linterNames)

	for _, linterName := range linterNames {
		prop := linterSettingsProps[linterName]
		ref := strings.TrimPrefix(prop.Ref, "#/definitions/settings/definitions/")

		def, ok := settingsDefs[ref]
		if !ok {
			continue
		}

		generateStruct(&b, linterName, def)
	}

	src := []byte(b.String())

	formatted, err := format.Source(src)
	if err != nil {
		fmt.Fprintf(os.Stderr, "format generated output: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(*outputPath, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write output: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %d linter settings structs to %s\n", len(linterNames), *outputPath)
}

func generateStruct(b *strings.Builder, linterName string, def schemaDef) {
	structName := toPascalCase(linterName) + "Settings"

	fmt.Fprintf(b, "// %s is generated from golangci-lint's JSON Schema.\n", structName)

	propNames := make([]string, 0, len(def.Properties))
	for propName := range def.Properties {
		propNames = append(propNames, propName)
	}

	sort.Strings(propNames)

	if len(propNames) == 0 {
		fmt.Fprintf(b, "type %s struct{}\n\n", structName)
		generateToMap(b, structName, propNames)
		fmt.Fprintf(b, "var _ types.SettingsConverter = %s{}\n\n", structName)

		return
	}

	fmt.Fprintf(b, "type %s struct {\n", structName)

	for _, propName := range propNames {
		propDef := def.Properties[propName]
		goType := schemaTypeToGo(propDef)
		fieldName := toPascalCase(propName)
		fmt.Fprintf(b, "\t%s %s `yaml:\"%s\"`\n", fieldName, goType, propName)
	}

	b.WriteString("}\n\n")

	generateToMap(b, structName, propNames)

	fmt.Fprintf(b, "var _ types.SettingsConverter = %s{}\n\n", structName)
}

func generateToMap(b *strings.Builder, structName string, fields []string) {
	fmt.Fprintf(b, "func (s %s) ToMap() map[string]any {\n", structName)
	b.WriteString("\treturn map[string]any{\n")

	for _, field := range fields {
		fmt.Fprintf(b, "\t\t%q: s.%s,\n", field, toPascalCase(field))
	}

	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
}

func schemaTypeToGo(def schemaDef) string {
	switch def.Type {
	case "string":
		return "string"
	case "integer":
		return "int"
	case "boolean":
		return "bool"
	case "number":
		return "float64"
	case "array":
		if def.Items != nil {
			return "[]" + schemaTypeToGo(*def.Items)
		}

		return "[]any"
	case "object":
		return "map[string]any"
	default:
		return "any"
	}
}

func toPascalCase(s string) string {
	if s == "" {
		return ""
	}

	s = strings.ReplaceAll(s, "-", "_")
	parts := strings.Split(s, "_")

	var b strings.Builder

	for _, part := range parts {
		if part == "" {
			continue
		}

		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}

	return b.String()
}

// isNewerVersion reports whether a is a strictly newer golangci-lint version
// than b. Both are "vMAJOR.MINOR.PATCH" strings; empty input yields
// (false, false) so callers can skip the comparison for untagged snapshots.
func isNewerVersion(a, b string) (bool, bool) {
	if a == "" || b == "" {
		return false, false
	}

	aParts, aOK := parseVersionParts(a)
	bParts, bOK := parseVersionParts(b)
	if !aOK || !bOK {
		return false, false
	}

	for i := range aParts {
		if aParts[i] != bParts[i] {
			return aParts[i] > bParts[i], true
		}
	}

	return false, true
}

func parseVersionParts(v string) ([3]int, bool) {
	var parts [3]int

	trimmed := strings.TrimPrefix(v, "v")
	chunks := strings.Split(trimmed, ".")
	if len(chunks) == 0 || len(chunks) > 3 {
		return parts, false
	}

	for i, chunk := range chunks {
		n, err := strconv.Atoi(chunk)
		if err != nil || n < 0 {
			return parts, false
		}

		parts[i] = n
	}

	return parts, true
}

func orUnknown(v string) string {
	if v == "" {
		return "unknown (pass -schema-version when regenerating)"
	}

	return v
}
