package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"charm.land/log/v2"
	apperrors "github.com/larsartmann/golangcli-linter-auto-configure/pkg/errors"
	"github.com/spf13/cobra"
)

// NewInstallHookCommand creates the install-hook command.
func NewInstallHookCommand(logger *log.Logger) *cobra.Command {
	return &cobra.Command{
		Use:   "install-hook",
		Short: "Install pre-commit hook for git",
		Long: `Installs a pre-commit hook that runs golangci-linter-auto-configure before each commit.

The hook will:
1. Check if a .golangci.yml config exists
2. Run 'analyze' to check for configuration issues
3. Warn if optimizations are available

The hook is installed at .git/hooks/pre-commit`,
		RunE: func(_ *cobra.Command, _ []string) error {
			// Check if we're in a git repository
			if _, err := os.Stat(".git"); os.IsNotExist(err) {
				return apperrors.ErrNotGitRepository
			}

			hookDir := ".git/hooks"
			hookPath := filepath.Join(hookDir, "pre-commit")

			// Create hook content
			hookContent := `#!/bin/bash
# Pre-commit hook for golangci-linter-auto-configure
# Auto-generated by golangci-linter-auto-configure install-hook

set -e

echo "Running golangci-linter-auto-configure pre-commit hook..."

# Check if golangci-linter-auto-configure is installed
if ! command -v golangci-linter-auto-configure &> /dev/null; then
    echo "Error: golangci-linter-auto-configure is not installed"
    echo "Install from: https://github.com/LarsArtmann/golangcli-linter-auto-configure"
    exit 1
fi

# Find config file
CONFIG_FILE=""
for file in ".golangci.yml" ".golangci.yaml"; do
    if [ -f "$file" ]; then
        CONFIG_FILE="$file"
        break
    fi
done

if [ -z "$CONFIG_FILE" ]; then
    echo "No .golangci.yml config found, skipping..."
    exit 0
fi

echo "Found config: $CONFIG_FILE"

# Run analyze
if ! golangci-linter-auto-configure analyze --config "$CONFIG_FILE"; then
    echo ""
    echo "Warning: Your configuration could be optimized"
    echo "Run 'golangci-linter-auto-configure configure' to auto-fix"
    echo ""
    # Don't block commit, just warn
fi

echo "Pre-commit hook completed!"
exit 0
`

			// Check if hook already exists
			if _, err := os.Stat(hookPath); err == nil {
				logger.Warnf("Pre-commit hook already exists at %s", hookPath)
				logger.Infof("Use --force to overwrite (not implemented yet)")

				return apperrors.ErrHookAlreadyExists
			}

			// Write hook file
			err := os.WriteFile(hookPath, []byte(hookContent), 0o755)
			if err != nil {
				return fmt.Errorf("failed to write hook: %w", err)
			}

			logger.Infof("✅ Pre-commit hook installed at %s", hookPath)
			logger.Infof("The hook will run on every commit to analyze your config")
			logger.Infof("To remove: rm %s", hookPath)

			return nil
		},
	}
}
