// Package gogenfilter provides project scanning for auto-generated Go files
// using the github.com/LarsArtmann/gogenfilter/v3 library.
//
// It detects files generated by sqlc, templ, protobuf, and other tools,
// then produces golangci-lint exclusion path patterns that can be injected
// into linters.exclusions.paths and formatters.exclusions.paths.
package gogenfilter

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	gogenfilter "github.com/LarsArtmann/gogenfilter/v3"
)

// GeneratedExclusion represents a path-based exclusion for auto-generated code.
type GeneratedExclusion struct {
	Path   string // glob pattern for golangci-lint exclusions.paths
	Reason string // human-readable reason for the exclusion
}

// String returns a human-readable representation of the exclusion.
func (e GeneratedExclusion) String() string {
	return fmt.Sprintf("%s (%s)", e.Path, e.Reason)
}

// ScanResult holds the results of scanning a project for generated files.
type ScanResult struct {
	Exclusions    []GeneratedExclusion
	ScannedFiles  int
	GeneratedFiles int
	Generators    []string // unique generator names detected
}

// ScanProject scans a project directory for auto-generated Go files
// and returns exclusion patterns suitable for golangci-lint configuration.
//
// It uses gogenfilter's two-phase detection (filename first, content second)
// to identify files generated by known tools (sqlc, templ, protobuf, etc.),
// then derives glob patterns to exclude them from linting.
func ScanProject(projectDir string) (*ScanResult, error) {
	opts, err := gogenfilter.WithFilterOptions(gogenfilter.FilterAll)
	if err != nil {
		return nil, fmt.Errorf("configure gogenfilter options: %w", err)
	}

	filter, err := gogenfilter.NewFilter(opts, gogenfilter.WithFS(os.DirFS(projectDir)))
	if err != nil {
		return nil, fmt.Errorf("create gogenfilter: %w", err)
	}

	goFiles, err := collectGoFiles(projectDir)
	if err != nil {
		return nil, fmt.Errorf("collect Go files: %w", err)
	}

	detectedByGenerator := make(map[string][]string)

	for _, file := range goFiles {
		result, err := filter.FilterDetailed(file)
		if err != nil {
			continue
		}

		if !result.Filtered || result.Reason == gogenfilter.ReasonNotFiltered {
			continue
		}

		generator := string(result.Reason)
		detectedByGenerator[generator] = append(detectedByGenerator[generator], file)
	}

	exclusions := deriveExclusionPatterns(detectedByGenerator, projectDir)

	generators := make([]string, 0, len(detectedByGenerator))
	for gen := range detectedByGenerator {
		generators = append(generators, gen)
	}
	sort.Strings(generators)

	generatedCount := 0
	for _, files := range detectedByGenerator {
		generatedCount += len(files)
	}

	return &ScanResult{
		Exclusions:     exclusions,
		ScannedFiles:   len(goFiles),
		GeneratedFiles: generatedCount,
		Generators:     generators,
	}, nil
}

// collectGoFiles walks the project directory and collects all .go file paths
// relative to the project root, excluding vendor and hidden directories.
func collectGoFiles(projectDir string) ([]string, error) {
	var goFiles []string

	err := filepath.WalkDir(projectDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if !d.IsDir() {
			if strings.HasSuffix(d.Name(), ".go") {
				rel, relErr := filepath.Rel(projectDir, path)
				if relErr != nil {
					return nil
				}

				goFiles = append(goFiles, rel)
			}

			return nil
		}

		if shouldSkipDir(d.Name(), path == projectDir) {
			return filepath.SkipDir
		}

		return nil
	})
	if err != nil {
		return nil, err
	}

	return goFiles, nil
}

func shouldSkipDir(name string, isRoot bool) bool {
	if isRoot {
		return false
	}

	if strings.HasPrefix(name, ".") {
		return true
	}

	return name == "vendor" || name == "node_modules"
}

// deriveExclusionPatterns converts detected generated files into glob patterns
// for golangci-lint exclusion configuration.
//
// For each generator type, it produces the minimal set of glob patterns that
// cover all detected files of that type.
func deriveExclusionPatterns(
	detectedByGenerator map[string][]string,
	projectDir string,
) []GeneratedExclusion {
	var exclusions []GeneratedExclusion

	generatorPatterns := map[string]struct {
		pattern string
		reason  string
	}{
		"templ":       {pattern: "**/*_templ.go", reason: "templ generated HTML components"},
		"protobuf":    {pattern: "**/*.pb.go", reason: "protobuf generated code"},
		"go-enum":     {pattern: "**/*_enum.go", reason: "go-enum generated enumerations"},
		"deepcopy-gen": {pattern: "**/zz_generated.*.go", reason: "deepcopy-gen generated code"},
		"wire":        {pattern: "**/wire_gen.go", reason: "wire generated dependency injection"},
		"moq":         {pattern: "**/*_moq.go", reason: "moq generated mocks"},
		"mockgen":     {pattern: "**/*_mock.go", reason: "mockgen generated mocks"},
		"stringer":    {pattern: "**/*_string.go", reason: "stringer generated string methods"},
	}

	for generator, files := range detectedByGenerator {
		pattern, reason := patternForGenerator(generator, files, projectDir, generatorPatterns)

		if pattern != "" {
			exclusions = append(exclusions, GeneratedExclusion{
				Path:   pattern,
				Reason: reason,
			})
		}
	}

	sort.Slice(exclusions, func(i, j int) bool {
		return exclusions[i].Path < exclusions[j].Path
	})

	return exclusions
}

func patternForGenerator(
	generator string,
	files []string,
	projectDir string,
	generatorPatterns map[string]struct {
		pattern string
		reason  string
	},
) (string, string) {
	if preset, ok := generatorPatterns[generator]; ok {
		return preset.pattern, preset.reason
	}

	if generator == "sqlc" {
		return sqlcPatterns(files, projectDir)
	}

	if generator == "oapi-codegen" {
		return oapiPatterns(files)
	}

	if generator == "generic" {
		return "", ""
	}

	return genericPatternFromFiles(files)
}

// sqlcPatterns generates exclusion patterns for sqlc files.
// Attempts to use sqlc config discovery for output directories,
// falling back to directory-based patterns from detected files.
func sqlcPatterns(files []string, projectDir string) (string, string) {
	dirs, err := gogenfilter.GetSQLOutputDirs([]string{projectDir})
	if err == nil && len(dirs) > 0 {
		patterns := make([]string, 0, len(dirs))
		for _, dir := range dirs {
			rel, relErr := filepath.Rel(projectDir, dir)
			if relErr != nil {
				rel = dir
			}

			patterns = append(patterns, rel+"/**")
		}

		slices.Sort(patterns)
		pattern := strings.Join(patterns, "|")

		return pattern, "sqlc generated database code"
	}

	return dirBasedPattern(files, "sqlc generated database code")
}

// oapiPatterns generates exclusion patterns for oapi-codegen files.
func oapiPatterns(files []string) (string, string) {
	genFiles := filterSuffix(files, ".gen.go")
	if len(genFiles) > 0 {
		return "**/*.gen.go", "oapi-codegen generated API code"
	}

	return dirBasedPattern(files, "oapi-codegen generated API code")
}

// dirBasedPattern generates a pattern covering the parent directories of the given files.
func dirBasedPattern(files []string, reason string) (string, string) {
	dirs := make(map[string]struct{})
	for _, f := range files {
		dirs[filepath.Dir(f)] = struct{}{}
	}

	dirList := make([]string, 0, len(dirs))
	for dir := range dirs {
		dirList = append(dirList, dir)
	}
	sort.Strings(dirList)

	patterns := make([]string, 0, len(dirList))
	for _, dir := range dirList {
		patterns = append(patterns, dir+"/**")
	}

	return strings.Join(patterns, "|"), reason
}

func filterSuffix(files []string, suffix string) []string {
	var filtered []string
	for _, f := range files {
		if strings.HasSuffix(f, suffix) {
			filtered = append(filtered, f)
		}
	}

	return filtered
}

func genericPatternFromFiles(files []string) (string, string) {
	if len(files) == 0 {
		return "", ""
	}

	return dirBasedPattern(files, "auto-generated code ("+filepath.Base(filepath.Dir(files[0]))+")")
}

// MergeExclusionPaths merges new exclusion paths into existing ones,
// avoiding duplicates. Returns the merged list sorted alphabetically.
func MergeExclusionPaths(existing, new []string) []string {
	seen := make(map[string]struct{}, len(existing))
	for _, p := range existing {
		seen[p] = struct{}{}
	}

	merged := make([]string, len(existing))
	copy(merged, existing)

	for _, p := range new {
		if _, ok := seen[p]; !ok {
			merged = append(merged, p)
			seen[p] = struct{}{}
		}
	}

	sort.Strings(merged)

	return merged
}

// ExclusionPaths extracts just the path patterns from a slice of exclusions.
func ExclusionPaths(exclusions []GeneratedExclusion) []string {
	paths := make([]string, len(exclusions))
	for i, e := range exclusions {
		paths[i] = e.Path
	}

	return paths
}
