package gogenfilter_test

import (
	"os"
	"path/filepath"
	"regexp"
	"testing"

	"github.com/LarsArtmann/gogenfilter/v3"
	gogenfilterinternal "github.com/larsartmann/golangci-lint-auto-configure/pkg/gogenfilter"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

const mainGoContent = "package main\nfunc main() {}"

func writeMainGo(dir string) {
	writeFile(dir, "main.go", mainGoContent)
}

func TestScanner(t *testing.T) {
	RegisterFailHandler(Fail) //art-dupl:accept Ginkgo per-package bootstrap
	RunSpecs(t, "GoGenFilter Scanner Suite")
}

var _ = Describe("Scanner", func() {
	Describe("ScanProject", func() {
		var tmpDir string

		BeforeEach(func() {
			tmpDir = GinkgoT().TempDir()
		})

		When("project has no generated files", func() {
			BeforeEach(func() {
				writeMainGo(tmpDir)
				writeFile(tmpDir, "handler.go", "package main\nfunc handler() {}")
			})

			It("returns empty exclusions", func() {
				result, err := gogenfilterinternal.ScanProject(os.DirFS(tmpDir), tmpDir)
				Expect(err).NotTo(HaveOccurred())
				Expect(result.Exclusions).To(BeEmpty())
				Expect(result.ScannedFiles).To(Equal(2))
				Expect(result.GeneratedFiles).To(Equal(0))
				Expect(result.Generators).To(BeEmpty())
			})
		})

		When("project has templ generated files", func() {
			BeforeEach(func() {
				writeMainGo(tmpDir)
				writeFile(
					tmpDir,
					"page_templ.go",
					"// Code generated by templ - DO NOT EDIT.\npackage main\nimport \"github.com/a-h/templ\"\nvar _ templ.Component",
				)
			})

			It("detects templ and returns exclusion pattern", func() {
				result, err := gogenfilterinternal.ScanProject(os.DirFS(tmpDir), tmpDir)
				Expect(err).NotTo(HaveOccurred())
				Expect(result.Exclusions).To(HaveLen(1))
				Expect(result.Exclusions[0].Path).To(Equal(`_templ\.go$`))
				Expect(result.Exclusions[0].Reason).To(ContainSubstring("templ"))
				Expect(result.Generators).To(ContainElement("templ"))
				Expect(result.GeneratedFiles).To(BeNumerically(">=", 1))
			})
		})

		When("project has protobuf generated files", func() {
			BeforeEach(func() {
				writeMainGo(tmpDir)
				writeFile(tmpDir, "user.pb.go", "// Code generated by protoc-gen-go.\npackage api")
			})

			It("detects protobuf and returns exclusion pattern", func() {
				result, err := gogenfilterinternal.ScanProject(os.DirFS(tmpDir), tmpDir)
				Expect(err).NotTo(HaveOccurred())
				Expect(result.Exclusions).To(HaveLen(1))
				Expect(result.Exclusions[0].Path).To(Equal(`\.pb\.go$`))
				Expect(result.Generators).To(ContainElement("protobuf"))
			})
		})

		When("project has multiple generator types", func() {
			BeforeEach(func() {
				writeMainGo(tmpDir)
				writeFile(
					tmpDir,
					"page_templ.go",
					"// Code generated by templ - DO NOT EDIT.\npackage main\nimport \"github.com/a-h/templ\"\nvar _ templ.Component",
				)
				writeFile(tmpDir, "api/user.pb.go", "// Code generated by protoc-gen-go.\npackage api")
				writeFile(tmpDir, "wire_gen.go", "// Code generated by Wire.\npackage main")
			})

			It("detects all generators and returns patterns for each", func() {
				result, err := gogenfilterinternal.ScanProject(os.DirFS(tmpDir), tmpDir)
				Expect(err).NotTo(HaveOccurred())
				Expect(result.Generators).To(ContainElements("templ", "protobuf", "wire"))
				Expect(result.Exclusions).To(HaveLen(3))

				paths := gogenfilterinternal.ExclusionPaths(result.Exclusions)
				Expect(paths).To(ContainElements(`_templ\.go$`, `\.pb\.go$`, `wire_gen\.go$`))
			})
		})

		When("project has wire generated files in different directories", func() {
			BeforeEach(func() {
				writeMainGo(tmpDir)
				writeFile(tmpDir, "wire_gen.go", "// Code generated by Wire.\npackage main")
			})

			It("returns a single pattern since wire has a fixed filename", func() {
				result, err := gogenfilterinternal.ScanProject(os.DirFS(tmpDir), tmpDir)
				Expect(err).NotTo(HaveOccurred())
				Expect(result.Exclusions).To(HaveLen(1))
				Expect(result.Exclusions[0].Path).To(Equal(`wire_gen\.go$`))
			})
		})

		When("project has files in excluded directories", func() {
			tests := []struct {
				desc    string
				relPath string
				pkgName string
			}{
				{"vendor directory", "vendor/page_templ.go", "vendor"},
				{"hidden directory", ".cache/page_templ.go", "cache"},
			}

			for _, tc := range tests {
				When("files are in "+tc.desc, func() {
					BeforeEach(func() {
						writeMainGo(tmpDir)
						writeFile(
							tmpDir,
							tc.relPath,
							"// Code generated by templ - DO NOT EDIT.\npackage "+tc.pkgName+"\nimport \"github.com/a-h/templ\"\nvar _ templ.Component",
						)
					})

					It("does not scan "+tc.desc, func() {
						result, err := gogenfilterinternal.ScanProject(os.DirFS(tmpDir), tmpDir)
						Expect(err).NotTo(HaveOccurred())
						Expect(result.Exclusions).To(BeEmpty())
					})
				})
			}
		})

		When("project has generic generated files", func() {
			BeforeEach(func() {
				writeMainGo(tmpDir)
				writeFile(tmpDir, "generated.go", "// Code generated by mytool - DO NOT EDIT\npackage main")
			})

			It("detects generic generated files but does not add path exclusion", func() {
				result, err := gogenfilterinternal.ScanProject(os.DirFS(tmpDir), tmpDir)
				Expect(err).NotTo(HaveOccurred())
				Expect(result.Generators).To(ContainElement("generic"))
				Expect(result.GeneratedFiles).To(BeNumerically(">=", 1))
			})
		})

		When("project has moq generated files", func() {
			BeforeEach(func() {
				writeMainGo(tmpDir)
				writeFile(tmpDir, "service_moq.go", "// Code generated by moq; DO NOT EDIT.\npackage main")
			})

			It("detects moq and returns exclusion pattern", func() {
				result, err := gogenfilterinternal.ScanProject(os.DirFS(tmpDir), tmpDir)
				Expect(err).NotTo(HaveOccurred())
				if result.GeneratedFiles > 0 {
					Expect(result.Generators).To(ContainElement("moq"))
					Expect(result.Exclusions).To(ContainElement(
						HaveField("Path", `_moq\.go$`),
					))
				}
			})
		})

		When("project has mockgen generated files", func() {
			BeforeEach(func() {
				writeMainGo(tmpDir)
				writeFile(tmpDir, "service_mock.go", "// Code generated by MockGen.\npackage main")
			})

			It("detects mockgen and returns exclusion pattern", func() {
				result, err := gogenfilterinternal.ScanProject(os.DirFS(tmpDir), tmpDir)
				Expect(err).NotTo(HaveOccurred())
				if result.GeneratedFiles > 0 {
					Expect(result.Generators).To(ContainElement("mockgen"))
					Expect(result.Exclusions).To(ContainElement(
						HaveField("Path", `_mock\.go$`),
					))
				}
			})
		})

		When("project has stringer generated files", func() {
			BeforeEach(func() {
				writeMainGo(tmpDir)
				writeFile(tmpDir, "status_string.go", "// Code generated by \"stringer\"; DO NOT EDIT.\npackage main")
			})

			It("detects stringer and returns exclusion pattern", func() {
				result, err := gogenfilterinternal.ScanProject(os.DirFS(tmpDir), tmpDir)
				Expect(err).NotTo(HaveOccurred())
				if result.GeneratedFiles > 0 {
					Expect(result.Generators).To(ContainElement("stringer"))
					Expect(result.Exclusions).To(ContainElement(
						HaveField("Path", `_string\.go$`),
					))
				}
			})
		})

		When("project has go-enum generated files", func() {
			BeforeEach(func() {
				writeMainGo(tmpDir)
				writeFile(tmpDir, "status_enum.go", "// Code generated by go-enum; DO NOT EDIT.\npackage main")
			})

			It("detects go-enum and returns exclusion pattern", func() {
				result, err := gogenfilterinternal.ScanProject(os.DirFS(tmpDir), tmpDir)
				Expect(err).NotTo(HaveOccurred())
				if result.GeneratedFiles > 0 {
					Expect(result.Generators).To(ContainElement("go-enum"))
					Expect(result.Exclusions).To(ContainElement(
						HaveField("Path", `_enum\.go$`),
					))
				}
			})
		})

		When("project has oapi-codegen generated files", func() {
			BeforeEach(func() {
				writeMainGo(tmpDir)
				writeFile(tmpDir, "api.gen.go", "// Code generated by github.com/oapi-codegen/oapi-codegen/v2; DO NOT EDIT.\npackage api")
			})

			It("detects oapi-codegen and returns exclusion pattern", func() {
				result, err := gogenfilterinternal.ScanProject(os.DirFS(tmpDir), tmpDir)
				Expect(err).NotTo(HaveOccurred())
				if result.GeneratedFiles > 0 {
					Expect(result.Generators).To(ContainElement("oapi-codegen"))
				}
			})
		})

		When("project has deepcopy-gen generated files", func() {
			BeforeEach(func() {
				writeMainGo(tmpDir)
				writeFile(
					tmpDir,
					"zz_generated.deepcopy.go",
					"// Code generated by deepcopy-gen; DO NOT EDIT.\npackage main",
				)
			})

			It("detects deepcopy-gen and returns exclusion pattern", func() {
				result, err := gogenfilterinternal.ScanProject(os.DirFS(tmpDir), tmpDir)
				Expect(err).NotTo(HaveOccurred())
				if result.GeneratedFiles > 0 {
					Expect(result.Generators).To(ContainElement("deepcopy-gen"))
					Expect(result.Exclusions).To(ContainElement(
						HaveField("Path", `zz_generated\..*\.go$`),
					))
				}
			})
		})

		When("project has files in node_modules", func() {
			BeforeEach(func() {
				writeMainGo(tmpDir)
				writeFile(
					tmpDir,
					"node_modules/page_templ.go",
					"// Code generated by templ - DO NOT EDIT.\npackage main\nimport \"github.com/a-h/templ\"\nvar _ templ.Component",
				)
			})

			It("does not scan node_modules", func() {
				result, err := gogenfilterinternal.ScanProject(os.DirFS(tmpDir), tmpDir)
				Expect(err).NotTo(HaveOccurred())
				Expect(result.Exclusions).To(BeEmpty())
			})
		})

		When("exclusion patterns are produced", func() {
			It("never contains pipe characters", func() {
				writeMainGo(tmpDir)
				writeFile(
					tmpDir,
					"page_templ.go",
					"// Code generated by templ - DO NOT EDIT.\npackage main\nimport \"github.com/a-h/templ\"\nvar _ templ.Component",
				)

				result, err := gogenfilterinternal.ScanProject(os.DirFS(tmpDir), tmpDir)
				Expect(err).NotTo(HaveOccurred())

				for _, excl := range result.Exclusions {
					Expect(excl.Path).NotTo(ContainSubstring("|"),
						"Exclusion path should not contain pipe delimiter: %s", excl.Path)
				}
			})

			It("produces valid regex patterns", func() {
				writeMainGo(tmpDir)
				writeFile(
					tmpDir,
					"page_templ.go",
					"// Code generated by templ - DO NOT EDIT.\npackage main\nimport \"github.com/a-h/templ\"\nvar _ templ.Component",
				)

				result, err := gogenfilterinternal.ScanProject(os.DirFS(tmpDir), tmpDir)
				Expect(err).NotTo(HaveOccurred())

				for _, excl := range result.Exclusions {
					_, regexErr := regexp.Compile(excl.Path)
					Expect(regexErr).NotTo(HaveOccurred(),
						"Exclusion path should be valid regex: %q", excl.Path)
				}
			})
		})
	})

	Describe("MergeExclusionPaths", func() {
		When("merging new paths into empty existing", func() {
			It("returns all new paths sorted", func() {
				result := gogenfilterinternal.MergeExclusionPaths(
					[]string{},
					[]string{`_templ\.go$`, `\.pb\.go$`},
				)
				Expect(result).To(Equal([]string{`\.pb\.go$`, `_templ\.go$`}))
			})
		})

		When("merging with duplicates", func() {
			It("deduplicates", func() {
				result := gogenfilterinternal.MergeExclusionPaths(
					[]string{`_templ\.go$`},
					[]string{`_templ\.go$`, `\.pb\.go$`},
				)
				Expect(result).To(Equal([]string{`\.pb\.go$`, `_templ\.go$`}))
			})
		})

		When("all new paths already exist", func() {
			It("returns unchanged list", func() {
				existing := []string{`\.pb\.go$`, `_templ\.go$`}
				result := gogenfilterinternal.MergeExclusionPaths(
					existing,
					[]string{`_templ\.go$`},
				)
				Expect(result).To(Equal(existing))
			})
		})
	})

	Describe("ExclusionPaths", func() {
		It("extracts just path patterns", func() {
			exclusions := []gogenfilterinternal.GeneratedExclusion{
				{Path: `_templ\.go$`, Reason: "templ"},
				{Path: `\.pb\.go$`, Reason: "protobuf"},
			}
			Expect(gogenfilterinternal.ExclusionPaths(exclusions)).To(Equal(
				[]string{`_templ\.go$`, `\.pb\.go$`},
			))
		})
	})

	Describe("GeneratedExclusion.String", func() {
		It("includes path and reason", func() {
			e := gogenfilterinternal.GeneratedExclusion{
				Path: `_templ\.go$`, Reason: "templ generated HTML components",
			}
			Expect(e.String()).To(Equal(`_templ\.go$ (templ generated HTML components)`))
		})
	})
})

func writeFile(dir, name, content string) {
	fullPath := filepath.Join(dir, name)

	err := os.MkdirAll(filepath.Dir(fullPath), 0o755)
	if err != nil {
		panic(err)
	}

	err = os.WriteFile(fullPath, []byte(content), 0o644)
	if err != nil {
		panic(err)
	}
}

// Verify gogenfilter v3 is imported correctly.
var _ gogenfilter.FilterOption
