// Package gogenfilter provides project scanning for auto-generated Go files
// using the github.com/LarsArtmann/gogenfilter/v3 library.
//
// It detects files generated by sqlc, templ, protobuf, and other tools,
// then produces golangci-lint exclusion path patterns that can be injected
// into linters.exclusions.paths and formatters.exclusions.paths.
package gogenfilter

import (
	"fmt"
	"io/fs"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	gogenfilter "github.com/LarsArtmann/gogenfilter/v3"
)

// GeneratedExclusion represents a path-based exclusion for auto-generated code.
type GeneratedExclusion struct {
	Path   string // regex pattern for golangci-lint exclusions.paths
	Reason string // human-readable reason for the exclusion
}

// String returns a human-readable representation of the exclusion.
func (e GeneratedExclusion) String() string {
	return fmt.Sprintf("%s (%s)", e.Path, e.Reason)
}

// ScanResult holds the results of scanning a project for generated files.
type ScanResult struct {
	Exclusions     []GeneratedExclusion
	ScannedFiles   int
	GeneratedFiles int
	Generators     []string // unique generator names detected
}

// ScanProject scans a project directory for auto-generated Go files
// and returns exclusion patterns suitable for golangci-lint configuration.
//
// It uses gogenfilter's two-phase detection (filename first, content second)
// to identify files generated by known tools (sqlc, templ, protobuf, etc.),
// then derives regex patterns to exclude them from linting.
// golangci-lint exclusions.paths uses RE2 regex syntax.
//
// The fsys parameter provides the filesystem to scan; use os.DirFS(projectDir)
// for the real filesystem. projectDir is used for sqlc config discovery.
func ScanProject(fsys fs.FS, projectDir string) (*ScanResult, error) {
	opts, err := gogenfilter.WithFilterOptions(gogenfilter.FilterAll)
	if err != nil {
		return nil, fmt.Errorf("configure gogenfilter options: %w", err)
	}

	filter, err := gogenfilter.NewFilter(opts, gogenfilter.WithFS(fsys))
	if err != nil {
		return nil, fmt.Errorf("create gogenfilter: %w", err)
	}

	goFiles, err := collectGoFiles(fsys)
	if err != nil {
		return nil, fmt.Errorf("collect Go files: %w", err)
	}

	detectedByGenerator := make(map[string][]string)

	for _, file := range goFiles {
		result, err := filter.FilterDetailed(file)
		if err != nil {
			continue
		}

		if !result.Filtered || result.Reason == gogenfilter.ReasonNotFiltered {
			continue
		}

		generator := string(result.Reason)
		detectedByGenerator[generator] = append(detectedByGenerator[generator], file)
	}

	exclusions := deriveExclusionPatterns(detectedByGenerator, projectDir)

	generators := make([]string, 0, len(detectedByGenerator))
	for gen := range detectedByGenerator {
		generators = append(generators, gen)
	}

	sort.Strings(generators)

	generatedCount := 0
	for _, files := range detectedByGenerator {
		generatedCount += len(files)
	}

	return &ScanResult{
		Exclusions:     exclusions,
		ScannedFiles:   len(goFiles),
		GeneratedFiles: generatedCount,
		Generators:     generators,
	}, nil
}

// collectGoFiles walks the filesystem and collects all .go file paths
// relative to the root, excluding vendor and hidden directories.
func collectGoFiles(fsys fs.FS) ([]string, error) {
	var goFiles []string

	err := fs.WalkDir(fsys, ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if !d.IsDir() {
			if strings.HasSuffix(d.Name(), ".go") {
				goFiles = append(goFiles, path)
			}

			return nil
		}

		if path != "." && shouldSkipDir(d.Name()) {
			return fs.SkipDir
		}

		return nil
	})
	if err != nil {
		return nil, err
	}

	return goFiles, nil
}

func shouldSkipDir(name string) bool {
	if strings.HasPrefix(name, ".") {
		return true
	}

	return name == "vendor" || name == "node_modules"
}

// deriveExclusionPatterns converts detected generated files into regex patterns
// for golangci-lint exclusion configuration.
//
// golangci-lint exclusions.paths uses RE2 regex syntax (compiled via regexp.Compile).
// Each pattern is an individual entry because golangci-lint expects separate paths entries.
func deriveExclusionPatterns(
	detectedByGenerator map[string][]string,
	projectDir string,
) []GeneratedExclusion {
	generatorPatterns := map[string]struct {
		pattern string
		reason  string
	}{
		"templ":        {pattern: `_templ\.go$`, reason: "templ generated HTML components"},
		"protobuf":     {pattern: `\.pb\.go$`, reason: "protobuf generated code"},
		"go-enum":      {pattern: `_enum\.go$`, reason: "go-enum generated enumerations"},
		"deepcopy-gen": {pattern: `zz_generated\..*\.go$`, reason: "deepcopy-gen generated code"},
		"wire":         {pattern: `wire_gen\.go$`, reason: "wire generated dependency injection"},
		"moq":          {pattern: `_moq\.go$`, reason: "moq generated mocks"},
		"mockgen":      {pattern: `_mock\.go$`, reason: "mockgen generated mocks"},
		"stringer":     {pattern: `_string\.go$`, reason: "stringer generated string methods"},
	}

	var exclusions []GeneratedExclusion

	for generator, files := range detectedByGenerator {
		exclusions = append(exclusions, exclusionsForGenerator(generator, files, projectDir, generatorPatterns)...)
	}

	sort.Slice(exclusions, func(i, j int) bool {
		return exclusions[i].Path < exclusions[j].Path
	})

	return exclusions
}

// exclusionsForGenerator returns one or more exclusion patterns for a given generator type.
func exclusionsForGenerator(
	generator string,
	files []string,
	projectDir string,
	generatorPatterns map[string]struct {
		pattern string
		reason  string
	},
) []GeneratedExclusion {
	if preset, ok := generatorPatterns[generator]; ok {
		return []GeneratedExclusion{{Path: preset.pattern, Reason: preset.reason}}
	}

	switch generator {
	case "sqlc":
		return sqlcExclusions(files, projectDir)
	case "oapi-codegen":
		return oapiExclusions(files)
	case "generic":
		return nil
	default:
		return dirBasedExclusions(files, "auto-generated code")
	}
}

// sqlcExclusions generates exclusion patterns for sqlc files.
// Attempts to use sqlc config discovery for output directories,
// falling back to directory-based patterns from detected files.
func sqlcExclusions(files []string, projectDir string) []GeneratedExclusion {
	const reason = "sqlc generated database code"

	dirs, err := gogenfilter.GetSQLOutputDirs([]string{projectDir})
	if err == nil && len(dirs) > 0 {
		patterns := make([]string, 0, len(dirs))
		for _, dir := range dirs {
			rel, relErr := filepath.Rel(projectDir, dir)
			if relErr != nil {
				rel = dir
			}

			patterns = append(patterns, regexp.QuoteMeta(rel)+"/")
		}

		return exclusionsFromDirs(patterns, reason)
	}

	return dirBasedExclusions(files, reason)
}

// oapiExclusions generates exclusion patterns for oapi-codegen files.
func oapiExclusions(files []string) []GeneratedExclusion {
	for _, f := range files {
		if strings.HasSuffix(f, ".gen.go") {
			return []GeneratedExclusion{
				{Path: `\.gen\.go$`, Reason: "oapi-codegen generated API code"},
			}
		}
	}

	return dirBasedExclusions(files, "oapi-codegen generated API code")
}

// dirBasedExclusions generates one exclusion entry per unique parent directory.
func dirBasedExclusions(files []string, reason string) []GeneratedExclusion {
	dirSet := make(map[string]struct{})
	for _, f := range files {
		dirSet[filepath.Dir(f)] = struct{}{}
	}

	dirs := make([]string, 0, len(dirSet))
	for dir := range dirSet {
		dirs = append(dirs, dir)
	}

	patterns := make([]string, 0, len(dirs))
	for _, dir := range dirs {
		patterns = append(patterns, regexp.QuoteMeta(dir)+"/")
	}

	return exclusionsFromDirs(patterns, reason)
}

// exclusionsFromDirs converts directory-based patterns into individual exclusion entries.
func exclusionsFromDirs(dirPatterns []string, reason string) []GeneratedExclusion {
	sort.Strings(dirPatterns)

	exclusions := make([]GeneratedExclusion, len(dirPatterns))
	for i, p := range dirPatterns {
		exclusions[i] = GeneratedExclusion{Path: p, Reason: reason}
	}

	return exclusions
}

// MergeExclusionPaths merges new exclusion paths into existing ones,
// avoiding duplicates. Returns the merged list sorted alphabetically.
func MergeExclusionPaths(existing, newPaths []string) []string {
	seen := make(map[string]struct{}, len(existing))
	for _, p := range existing {
		seen[p] = struct{}{}
	}

	merged := make([]string, len(existing))
	copy(merged, existing)

	for _, p := range newPaths {
		if _, ok := seen[p]; !ok {
			merged = append(merged, p)
			seen[p] = struct{}{}
		}
	}

	sort.Strings(merged)

	return merged
}

// ExclusionPaths extracts just the path patterns from a slice of exclusions.
func ExclusionPaths(exclusions []GeneratedExclusion) []string {
	paths := make([]string, len(exclusions))
	for i, e := range exclusions {
		paths[i] = e.Path
	}

	return paths
}
