// Package gogenfilter provides project scanning for auto-generated Go files
// using the github.com/LarsArtmann/gogenfilter/v3 library.
//
// Detection and exclusion-pattern derivation are fully delegated to gogenfilter:
// generators whose detected files all follow a fixed filename convention produce
// per-file regex patterns, and the rest produce anchored directory patterns only
// for fully generated directories, precise per-file patterns otherwise. The
// patterns can be injected into linters.exclusions.paths and
// formatters.exclusions.paths.
package gogenfilter

import (
	"fmt"
	"io/fs"

	gogenfilter "github.com/LarsArtmann/gogenfilter/v3"
	errorfamily "github.com/larsartmann/go-error-family"
	"github.com/larsartmann/golangci-lint-auto-configure/pkg/types"
)

// GeneratedExclusion represents a path-based exclusion for auto-generated code.
type GeneratedExclusion struct {
	Path   string // regex pattern for golangci-lint exclusions.paths
	Reason string // human-readable reason for the exclusion
}

// String returns a human-readable representation of the exclusion.
func (e GeneratedExclusion) String() string {
	return fmt.Sprintf("%s (%s)", e.Path, e.Reason)
}

// ScanResult holds the results of scanning a project for generated files.
type ScanResult struct {
	Exclusions     []GeneratedExclusion
	ScannedFiles   int
	GeneratedFiles int
	Generators     []string // unique generator names detected
}

// ScanProject scans a project directory for auto-generated Go files
// and returns exclusion patterns suitable for golangci-lint configuration.
//
// It delegates to gogenfilter's scanner, which detects files generated by known
// tools (sqlc, templ, protobuf, mockery, etc.) and derives RE2 regex patterns
// for golangci-lint exclusions.paths: fixed filename-convention patterns when
// they cover every detected file of a generator, anchored directory patterns
// only for fully generated directories, and precise per-file patterns otherwise.
func ScanProject(fsys fs.FS) (*ScanResult, error) {
	result, err := gogenfilter.ScanProject(fsys)
	if err != nil {
		return nil, errorfamily.WrapTransientf(err, "scanner.scan",
			"scan project for generated files")
	}

	exclusions := make([]GeneratedExclusion, 0, len(result.Exclusions))
	for _, exclusion := range result.Exclusions {
		exclusions = append(exclusions, GeneratedExclusion{
			Path:   exclusion.Pattern,
			Reason: exclusion.Reason,
		})
	}

	return &ScanResult{
		Exclusions:     exclusions,
		ScannedFiles:   result.ScannedFiles,
		GeneratedFiles: len(result.Files),
		Generators:     result.Generators,
	}, nil
}

// MergeExclusionPaths merges new exclusion paths into existing ones,
// avoiding duplicates. Returns the merged list sorted alphabetically.
func MergeExclusionPaths(existing, newPaths []string) []string {
	result := types.NewSet(existing...)

	for _, p := range newPaths {
		result.Add(p)
	}

	return types.ToSortedSlice(result)
}

// ExclusionPaths extracts just the path patterns from a slice of exclusions.
func ExclusionPaths(exclusions []GeneratedExclusion) []string {
	paths := make([]string, len(exclusions))
	for i, e := range exclusions {
		paths[i] = e.Path
	}

	return paths
}
