package gogenfilter_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/LarsArtmann/gogenfilter/v3"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	gogenfilterinternal "github.com/larsartmann/golangci-lint-auto-configure/pkg/gogenfilter"
)

func TestScanner(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "GoGenFilter Scanner Suite")
}

var _ = Describe("Scanner", func() {
	Describe("ScanProject", func() {
		var tmpDir string

		BeforeEach(func() {
			tmpDir = GinkgoT().TempDir()
		})

		When("project has no generated files", func() {
			BeforeEach(func() {
				writeFile(tmpDir, "main.go", "package main\nfunc main() {}")
				writeFile(tmpDir, "handler.go", "package main\nfunc handler() {}")
			})

			It("returns empty exclusions", func() {
				result, err := gogenfilterinternal.ScanProject(tmpDir)
				Expect(err).NotTo(HaveOccurred())
				Expect(result.Exclusions).To(BeEmpty())
				Expect(result.ScannedFiles).To(Equal(2))
				Expect(result.GeneratedFiles).To(Equal(0))
				Expect(result.Generators).To(BeEmpty())
			})
		})

		When("project has templ generated files", func() {
			BeforeEach(func() {
				writeFile(tmpDir, "main.go", "package main\nfunc main() {}")
				writeFile(tmpDir, "page_templ.go", "// Code generated by templ - DO NOT EDIT.\npackage main\nimport \"github.com/a-h/templ\"\nvar _ templ.Component")
			})

			It("detects templ and returns exclusion pattern", func() {
				result, err := gogenfilterinternal.ScanProject(tmpDir)
				Expect(err).NotTo(HaveOccurred())
				Expect(result.Exclusions).To(HaveLen(1))
				Expect(result.Exclusions[0].Path).To(Equal("**/*_templ.go"))
				Expect(result.Exclusions[0].Reason).To(ContainSubstring("templ"))
				Expect(result.Generators).To(ContainElement("templ"))
				Expect(result.GeneratedFiles).To(BeNumerically(">=", 1))
			})
		})

		When("project has protobuf generated files", func() {
			BeforeEach(func() {
				writeFile(tmpDir, "main.go", "package main\nfunc main() {}")
				writeFile(tmpDir, "user.pb.go", "// Code generated by protoc-gen-go.\npackage api")
			})

			It("detects protobuf and returns exclusion pattern", func() {
				result, err := gogenfilterinternal.ScanProject(tmpDir)
				Expect(err).NotTo(HaveOccurred())
				Expect(result.Exclusions).To(HaveLen(1))
				Expect(result.Exclusions[0].Path).To(Equal("**/*.pb.go"))
				Expect(result.Generators).To(ContainElement("protobuf"))
			})
		})

		When("project has multiple generator types", func() {
			BeforeEach(func() {
				writeFile(tmpDir, "main.go", "package main\nfunc main() {}")
				writeFile(tmpDir, "page_templ.go", "// Code generated by templ - DO NOT EDIT.\npackage main\nimport \"github.com/a-h/templ\"\nvar _ templ.Component")
				writeFile(tmpDir, "api/user.pb.go", "// Code generated by protoc-gen-go.\npackage api")
				writeFile(tmpDir, "wire_gen.go", "// Code generated by Wire.\npackage main")
			})

			It("detects all generators and returns patterns for each", func() {
				result, err := gogenfilterinternal.ScanProject(tmpDir)
				Expect(err).NotTo(HaveOccurred())
				Expect(result.Generators).To(ContainElements("templ", "protobuf", "wire"))
				Expect(result.Exclusions).To(HaveLen(3))

				paths := gogenfilterinternal.ExclusionPaths(result.Exclusions)
				Expect(paths).To(ContainElements("**/*_templ.go", "**/*.pb.go", "**/wire_gen.go"))
			})
		})

		When("project has files in vendor directory", func() {
			BeforeEach(func() {
				writeFile(tmpDir, "main.go", "package main\nfunc main() {}")
				writeFile(tmpDir, "vendor/page_templ.go", "// Code generated by templ - DO NOT EDIT.\npackage vendor\nimport \"github.com/a-h/templ\"\nvar _ templ.Component")
			})

			It("does not scan vendor directory", func() {
				result, err := gogenfilterinternal.ScanProject(tmpDir)
				Expect(err).NotTo(HaveOccurred())
				Expect(result.Exclusions).To(BeEmpty())
			})
		})

		When("project has files in hidden directories", func() {
			BeforeEach(func() {
				writeFile(tmpDir, "main.go", "package main\nfunc main() {}")
				writeFile(tmpDir, ".cache/page_templ.go", "// Code generated by templ - DO NOT EDIT.\npackage cache\nimport \"github.com/a-h/templ\"\nvar _ templ.Component")
			})

			It("does not scan hidden directories", func() {
				result, err := gogenfilterinternal.ScanProject(tmpDir)
				Expect(err).NotTo(HaveOccurred())
				Expect(result.Exclusions).To(BeEmpty())
			})
		})

		When("project has generic generated files", func() {
			BeforeEach(func() {
				writeFile(tmpDir, "main.go", "package main\nfunc main() {}")
				writeFile(tmpDir, "generated.go", "// Code generated by mytool - DO NOT EDIT\npackage main")
			})

			It("detects generic generated files but does not add path exclusion", func() {
				result, err := gogenfilterinternal.ScanProject(tmpDir)
				Expect(err).NotTo(HaveOccurred())
				Expect(result.Generators).To(ContainElement("generic"))
				Expect(result.GeneratedFiles).To(BeNumerically(">=", 1))
			})
		})
	})

	Describe("MergeExclusionPaths", func() {
		When("merging new paths into empty existing", func() {
			It("returns all new paths sorted", func() {
				result := gogenfilterinternal.MergeExclusionPaths(
					[]string{},
					[]string{"**/*_templ.go", "**/*.pb.go"},
				)
				Expect(result).To(Equal([]string{"**/*.pb.go", "**/*_templ.go"}))
			})
		})

		When("merging with duplicates", func() {
			It("deduplicates", func() {
				result := gogenfilterinternal.MergeExclusionPaths(
					[]string{"**/*_templ.go"},
					[]string{"**/*_templ.go", "**/*.pb.go"},
				)
				Expect(result).To(Equal([]string{"**/*.pb.go", "**/*_templ.go"}))
			})
		})

		When("all new paths already exist", func() {
			It("returns unchanged list", func() {
				existing := []string{"**/*.pb.go", "**/*_templ.go"}
				result := gogenfilterinternal.MergeExclusionPaths(
					existing,
					[]string{"**/*_templ.go"},
				)
				Expect(result).To(Equal(existing))
			})
		})
	})

	Describe("ExclusionPaths", func() {
		It("extracts just path patterns", func() {
			exclusions := []gogenfilterinternal.GeneratedExclusion{
				{Path: "**/*_templ.go", Reason: "templ"},
				{Path: "**/*.pb.go", Reason: "protobuf"},
			}
			Expect(gogenfilterinternal.ExclusionPaths(exclusions)).To(Equal(
				[]string{"**/*_templ.go", "**/*.pb.go"},
			))
		})
	})

	Describe("GeneratedExclusion.String", func() {
		It("includes path and reason", func() {
			e := gogenfilterinternal.GeneratedExclusion{
				Path: "**/*_templ.go", Reason: "templ generated HTML components",
			}
			Expect(e.String()).To(Equal("**/*_templ.go (templ generated HTML components)"))
		})
	})
})

func writeFile(dir, name, content string) {
	fullPath := filepath.Join(dir, name)

	if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
		panic(err)
	}

	if err := os.WriteFile(fullPath, []byte(content), 0o644); err != nil {
		panic(err)
	}
}

// Verify gogenfilter v3 is imported correctly.
var _ gogenfilter.FilterOption
