// Package constants provides centralized configuration values for the golangci-linter-auto-configure tool.
package constants

import "github.com/larsartmann/golangcli-linter-auto-configure/pkg/types"

// LinterPriorities maps linter names to their priority levels.
var LinterPriorities = map[types.LinterName]types.LinterPriority{
	// Critical linters - should ALWAYS be enabled
	"loggercheck": types.LinterPriorityCritical,
	"gosec":       types.LinterPriorityCritical,
	"errcheck":    types.LinterPriorityCritical,
	"staticcheck": types.LinterPriorityCritical,
	"govet":       types.LinterPriorityCritical,
	"errchkjson":  types.LinterPriorityCritical,
	"musttag":     types.LinterPriorityCritical,
	"sloglint":    types.LinterPriorityCritical,
	"nilerr":      types.LinterPriorityCritical,
	"noctx":       types.LinterPriorityCritical,

	// High value linters - recommended for most projects
	"wrapcheck":        types.LinterPriorityHigh,
	"errorlint":        types.LinterPriorityHigh,
	"prealloc":         types.LinterPriorityHigh,
	"unconvert":        types.LinterPriorityHigh,
	"ineffassign":      types.LinterPriorityHigh,
	"gocyclo":          types.LinterPriorityHigh,
	"funlen":           types.LinterPriorityHigh,
	"cyclop":           types.LinterPriorityHigh,
	"gocognit":         types.LinterPriorityHigh,
	"maintidx":         types.LinterPriorityHigh,
	"exhaustive":       types.LinterPriorityHigh,
	"exhaustruct":      types.LinterPriorityHigh,
	"goconst":          types.LinterPriorityHigh,
	"misspell":         types.LinterPriorityHigh,
	"revive":           types.LinterPriorityHigh,
	"nolintlint":       types.LinterPriorityHigh,
	"forcetypeassert":  types.LinterPriorityHigh,
	"gocritic":         types.LinterPriorityHigh,
	"unused":           types.LinterPriorityHigh,
	"bodyclose":        types.LinterPriorityHigh,
	"contextcheck":     types.LinterPriorityHigh,
	"dupl":             types.LinterPriorityHigh,
	"durationcheck":    types.LinterPriorityHigh,
	"errname":          types.LinterPriorityHigh,
	"gochecknoglobals": types.LinterPriorityHigh,
	"gochecknoinits":   types.LinterPriorityHigh,
	"gosmopolitan":     types.LinterPriorityHigh,
	"interfacebloat":   types.LinterPriorityHigh,
	"nestif":           types.LinterPriorityHigh,
	"nilnil":           types.LinterPriorityHigh,
	"nakedret":         types.LinterPriorityHigh,
	"paralleltest":     types.LinterPriorityHigh,
	"predeclared":      types.LinterPriorityHigh,
	"reassign":         types.LinterPriorityHigh,
	"rowserrcheck":     types.LinterPriorityHigh,
	"spancheck":        types.LinterPriorityHigh,
	"sqlclosecheck":    types.LinterPriorityHigh,
	"testifylint":      types.LinterPriorityHigh,
	"thelper":          types.LinterPriorityHigh,
	"unparam":          types.LinterPriorityHigh,
	"wastedassign":     types.LinterPriorityHigh,
	"copyloopvar":      types.LinterPriorityHigh,
	"ginkgolinter":     types.LinterPriorityHigh,
	"gochecksumtype":   types.LinterPriorityHigh,
	"intrange":         types.LinterPriorityHigh,
	"mirror":           types.LinterPriorityHigh,
	"perfsprint":       types.LinterPriorityHigh,
	"protogetter":      types.LinterPriorityHigh,
	"usetesting":       types.LinterPriorityHigh,
	"recvcheck":        types.LinterPriorityHigh,
	"nilnesserr":       types.LinterPriorityHigh,

	// Medium value linters - optional but recommended
	"dupword":                   types.LinterPriorityMedium,
	"godot":                     types.LinterPriorityMedium,
	"godox":                     types.LinterPriorityMedium,
	"goheader":                  types.LinterPriorityMedium,
	"gofmt":                     types.LinterPriorityMedium,
	"gci":                       types.LinterPriorityMedium,
	"varnamelen":                types.LinterPriorityMedium,
	"whitespace":                types.LinterPriorityMedium,
	"wsl_v5":                    types.LinterPriorityMedium,
	"grouper":                   types.LinterPriorityMedium,
	"dogsled":                   types.LinterPriorityMedium,
	"makezero":                  types.LinterPriorityMedium,
	"exportloopref":             types.LinterPriorityMedium,
	"asciicheck":                types.LinterPriorityMedium,
	"bidichk":                   types.LinterPriorityMedium,
	"containedctx":              types.LinterPriorityMedium,
	"decorder":                  types.LinterPriorityMedium,
	"depguard":                  types.LinterPriorityMedium,
	"forbidigo":                 types.LinterPriorityMedium,
	"godoclint":                 types.LinterPriorityMedium,
	"gomoddirectives":           types.LinterPriorityMedium,
	"gomodguard":                types.LinterPriorityMedium,
	"ireturn":                   types.LinterPriorityMedium,
	"lll":                       types.LinterPriorityMedium,
	"mnd":                       types.LinterPriorityMedium,
	"nlreturn":                  types.LinterPriorityMedium,
	"nonamedreturns":            types.LinterPriorityMedium,
	"promlinter":                types.LinterPriorityMedium,
	"tagliatelle":               types.LinterPriorityMedium,
	"testpackage":               types.LinterPriorityMedium,
	"tparallel":                 types.LinterPriorityMedium,
	"unqueryvet":                types.LinterPriorityMedium,
	"usestdlibvars":             types.LinterPriorityMedium,
	"asasalint":                 types.LinterPriorityMedium,
	"canonicalheader":           types.LinterPriorityMedium,
	"err113":                    types.LinterPriorityMedium,
	"exptostd":                  types.LinterPriorityMedium,
	"fatcontext":                types.LinterPriorityMedium,
	"funcorder":                 types.LinterPriorityMedium,
	"gocheckcompilerdirectives": types.LinterPriorityMedium,
	"goprintffuncname":          types.LinterPriorityMedium,
	"iface":                     types.LinterPriorityMedium,
	"inamedparam":               types.LinterPriorityMedium,
	"iotamixing":                types.LinterPriorityMedium,
	"modernize":                 types.LinterPriorityMedium,
	"noinlineerr":               types.LinterPriorityMedium,
	"nosprintfhostport":         types.LinterPriorityMedium,
	"tagalign":                  types.LinterPriorityMedium,
	"testableexamples":          types.LinterPriorityMedium,
	"imports":                   types.LinterPriorityHigh,
	"zerologlint":               types.LinterPriorityHigh,
	"arangolint":                types.LinterPriorityMedium,
	"embeddedstructfieldcheck":  types.LinterPriorityMedium,

	// All other linters default to Optional
}
