package constants

import "github.com/larsartmann/golangci-lint-auto-configure/pkg/types"

// LinterPriorities maps linter names to their priority levels.
var LinterPriorities = map[types.LinterName]types.LinterPriority{
	// Critical linters - should ALWAYS be enabled
	"loggercheck":  types.LinterPriorityCritical,
	"gosec":        types.LinterPriorityCritical,
	"errcheck":     types.LinterPriorityCritical,
	"staticcheck":  types.LinterPriorityCritical,
	"govet":        types.LinterPriorityCritical,
	"errchkjson":   types.LinterPriorityCritical,
	"musttag":      types.LinterPriorityCritical,
	"sloglint":     types.LinterPriorityCritical,
	"nilerr":       types.LinterPriorityCritical,
	"noctx":        types.LinterPriorityCritical,
	"paralleltest": types.LinterPriorityCritical,

	// High value linters - recommended for most projects
	"wrapcheck":        types.LinterPriorityHigh,
	"errorlint":        types.LinterPriorityHigh,
	"prealloc":         types.LinterPriorityHigh,
	"unconvert":        types.LinterPriorityHigh,
	"ineffassign":      types.LinterPriorityHigh,
	"gocyclo":          types.LinterPriorityHigh,
	"funlen":           types.LinterPriorityHigh,
	"cyclop":           types.LinterPriorityHigh,
	"gocognit":         types.LinterPriorityHigh,
	"maintidx":         types.LinterPriorityHigh,
	"exhaustive":       types.LinterPriorityHigh,
	"goconst":          types.LinterPriorityHigh,
	"misspell":         types.LinterPriorityHigh,
	"revive":           types.LinterPriorityHigh,
	"nolintlint":       types.LinterPriorityHigh,
	"forcetypeassert":  types.LinterPriorityHigh,
	"gocritic":         types.LinterPriorityHigh,
	"unused":           types.LinterPriorityHigh,
	"bodyclose":        types.LinterPriorityHigh,
	"contextcheck":     types.LinterPriorityHigh,
	"dupl":             types.LinterPriorityHigh,
	"durationcheck":    types.LinterPriorityHigh,
	"errname":          types.LinterPriorityHigh,
	"gochecknoglobals": types.LinterPriorityHigh,
	"gochecknoinits":   types.LinterPriorityHigh,
	"gosmopolitan":     types.LinterPriorityHigh,
	"interfacebloat":   types.LinterPriorityHigh,
	"nestif":           types.LinterPriorityHigh,
	"nilnil":           types.LinterPriorityHigh,
	"nakedret":         types.LinterPriorityHigh,
	"predeclared":      types.LinterPriorityHigh,
	"reassign":         types.LinterPriorityHigh,
	"rowserrcheck":     types.LinterPriorityHigh,
	"spancheck":        types.LinterPriorityHigh,
	"sqlclosecheck":    types.LinterPriorityHigh,
	"testifylint":      types.LinterPriorityHigh,
	"thelper":          types.LinterPriorityHigh,
	"unparam":          types.LinterPriorityHigh,
	"wastedassign":     types.LinterPriorityHigh,
	"copyloopvar":      types.LinterPriorityHigh,
	"ginkgolinter":     types.LinterPriorityHigh,
	"gochecksumtype":   types.LinterPriorityHigh,
	"intrange":         types.LinterPriorityHigh,
	"mirror":           types.LinterPriorityHigh,
	"perfsprint":       types.LinterPriorityHigh,
	"protogetter":      types.LinterPriorityHigh,
	"usetesting":       types.LinterPriorityHigh,
	"recvcheck":        types.LinterPriorityHigh,
	"nilnesserr":       types.LinterPriorityHigh,

	// Medium value linters - optional but recommended
	"exhaustruct_v5":            types.LinterPriorityMedium,
	"depguard":                  types.LinterPriorityMedium, // NeverAutoEnable: architectural enforcement via file-pattern rules (layer dependencies, feature isolation)
	"gohumanize":                types.LinterPriorityMedium, // golangci-lint v2 module plugin; project-specific (requires dustin/go-humanize dep + custom binary)
	"dupword":                   types.LinterPriorityMedium,
	"godot":                     types.LinterPriorityMedium,
	"godox":                     types.LinterPriorityMedium,
	"goheader":                  types.LinterPriorityMedium,
	"varnamelen":                types.LinterPriorityMedium,
	"whitespace":                types.LinterPriorityMedium,
	"wsl_v5":                    types.LinterPriorityMedium,
	"grouper":                   types.LinterPriorityMedium,
	"dogsled":                   types.LinterPriorityMedium,
	"makezero":                  types.LinterPriorityMedium,
	"asciicheck":                types.LinterPriorityMedium,
	"bidichk":                   types.LinterPriorityMedium,
	"containedctx":              types.LinterPriorityMedium,
	"decorder":                  types.LinterPriorityMedium,
	"forbidigo":                 types.LinterPriorityMedium,
	"godoclint":                 types.LinterPriorityMedium,
	"gomoddirectives":           types.LinterPriorityMedium,
	"gomodguard":                types.LinterPriorityMedium,
	"gomodguard_v2":             types.LinterPriorityMedium,
	"ireturn":                   types.LinterPriorityMedium,
	"lll":                       types.LinterPriorityMedium,
	"mnd":                       types.LinterPriorityMedium,
	"nlreturn":                  types.LinterPriorityMedium,
	"nonamedreturns":            types.LinterPriorityMedium,
	"promlinter":                types.LinterPriorityMedium,
	"tagliatelle":               types.LinterPriorityMedium,
	"testpackage":               types.LinterPriorityMedium,
	"tparallel":                 types.LinterPriorityMedium,
	"unqueryvet":                types.LinterPriorityMedium,
	"usestdlibvars":             types.LinterPriorityMedium,
	"asasalint":                 types.LinterPriorityMedium,
	"canonicalheader":           types.LinterPriorityMedium,
	"err113":                    types.LinterPriorityMedium,
	"exptostd":                  types.LinterPriorityMedium,
	"fatcontext":                types.LinterPriorityMedium,
	"gocheckcompilerdirectives": types.LinterPriorityMedium,
	"goprintffuncname":          types.LinterPriorityMedium,
	"iface":                     types.LinterPriorityMedium,
	"inamedparam":               types.LinterPriorityMedium,
	"iotamixing":                types.LinterPriorityMedium,
	"modernize":                 types.LinterPriorityMedium,
	"nosprintfhostport":         types.LinterPriorityMedium,
	"tagalign":                  types.LinterPriorityMedium,
	"testableexamples":          types.LinterPriorityMedium,
	"importas":                  types.LinterPriorityMedium,
	"zerologlint":               types.LinterPriorityHigh,
	"arangolint":                types.LinterPriorityMedium,
	"embeddedstructfieldcheck":  types.LinterPriorityMedium,
	"clickhouselint":            types.LinterPriorityMedium,

	// All other linters default to Optional
}

// CriticalLinters returns the names of the core critical linters that MUST
// be configured in every golangci-lint config for correctness checking.
// These are the fundamental linters (errcheck, staticcheck, govet) that
// the health check enforces. Other critical-priority linters (gosec, musttag,
// etc.) are also critical but the health check focuses on these three as
// the absolute minimum baseline.
func CriticalLinters() []types.LinterName {
	return []types.LinterName{"errcheck", "staticcheck", "govet"}
}
