// Code generated by go run ./cmd/generate-settings. DO NOT EDIT.
//
// Schema provenance:
//   Schema snapshot: unknown (pass -schema-version when regenerating)
//   Tool minimum:   v2.10.1 (pkg/constants.MinGolangCILintVersion)
//
// A schema snapshot NEWER than the tool minimum may contain keys that do
// not exist in older golangci-lint. The curated structs in
// linter_settings.go (the compiled truth) are schema-verified by the CI
// schema-verify job against the pinned golangci-lint version.
//go:build generate

package constants

import "github.com/larsartmann/golangci-lint-auto-configure/pkg/types"

// AsasalintSettings is generated from golangci-lint's JSON Schema.
type AsasalintSettings struct {
	Exclude              []string `yaml:"exclude"`
	UseBuiltinExclusions bool     `yaml:"use-builtin-exclusions"`
}

func (s AsasalintSettings) ToMap() map[string]any {
	return map[string]any{
		"exclude":                s.Exclude,
		"use-builtin-exclusions": s.UseBuiltinExclusions,
	}
}

var _ types.SettingsConverter = AsasalintSettings{}

// BidichkSettings is generated from golangci-lint's JSON Schema.
type BidichkSettings struct {
	FirstStrongIsolate       bool `yaml:"first-strong-isolate"`
	LeftToRightEmbedding     bool `yaml:"left-to-right-embedding"`
	LeftToRightIsolate       bool `yaml:"left-to-right-isolate"`
	LeftToRightOverride      bool `yaml:"left-to-right-override"`
	PopDirectionalFormatting bool `yaml:"pop-directional-formatting"`
	PopDirectionalIsolate    bool `yaml:"pop-directional-isolate"`
	RightToLeftEmbedding     bool `yaml:"right-to-left-embedding"`
	RightToLeftIsolate       bool `yaml:"right-to-left-isolate"`
	RightToLeftOverride      bool `yaml:"right-to-left-override"`
}

func (s BidichkSettings) ToMap() map[string]any {
	return map[string]any{
		"first-strong-isolate":       s.FirstStrongIsolate,
		"left-to-right-embedding":    s.LeftToRightEmbedding,
		"left-to-right-isolate":      s.LeftToRightIsolate,
		"left-to-right-override":     s.LeftToRightOverride,
		"pop-directional-formatting": s.PopDirectionalFormatting,
		"pop-directional-isolate":    s.PopDirectionalIsolate,
		"right-to-left-embedding":    s.RightToLeftEmbedding,
		"right-to-left-isolate":      s.RightToLeftIsolate,
		"right-to-left-override":     s.RightToLeftOverride,
	}
}

var _ types.SettingsConverter = BidichkSettings{}

// BodycloseSettings is generated from golangci-lint's JSON Schema.
type BodycloseSettings struct {
	CheckConsumption bool `yaml:"check-consumption"`
}

func (s BodycloseSettings) ToMap() map[string]any {
	return map[string]any{
		"check-consumption": s.CheckConsumption,
	}
}

var _ types.SettingsConverter = BodycloseSettings{}

// CopyloopvarSettings is generated from golangci-lint's JSON Schema.
type CopyloopvarSettings struct {
	CheckAlias bool `yaml:"check-alias"`
}

func (s CopyloopvarSettings) ToMap() map[string]any {
	return map[string]any{
		"check-alias": s.CheckAlias,
	}
}

var _ types.SettingsConverter = CopyloopvarSettings{}

// CustomSettings is generated from golangci-lint's JSON Schema.
type CustomSettings struct{}

func (s CustomSettings) ToMap() map[string]any {
	return map[string]any{}
}

var _ types.SettingsConverter = CustomSettings{}

// CyclopSettings is generated from golangci-lint's JSON Schema.
type CyclopSettings struct {
	MaxComplexity  int     `yaml:"max-complexity"`
	PackageAverage float64 `yaml:"package-average"`
}

func (s CyclopSettings) ToMap() map[string]any {
	return map[string]any{
		"max-complexity":  s.MaxComplexity,
		"package-average": s.PackageAverage,
	}
}

var _ types.SettingsConverter = CyclopSettings{}

// DecorderSettings is generated from golangci-lint's JSON Schema.
type DecorderSettings struct {
	DecOrder                  []any `yaml:"dec-order"`
	DisableConstDecNumCheck   bool  `yaml:"disable-const-dec-num-check"`
	DisableDecNumCheck        bool  `yaml:"disable-dec-num-check"`
	DisableDecOrderCheck      bool  `yaml:"disable-dec-order-check"`
	DisableInitFuncFirstCheck bool  `yaml:"disable-init-func-first-check"`
	DisableTypeDecNumCheck    bool  `yaml:"disable-type-dec-num-check"`
	DisableVarDecNumCheck     bool  `yaml:"disable-var-dec-num-check"`
	IgnoreUnderscoreVars      bool  `yaml:"ignore-underscore-vars"`
}

func (s DecorderSettings) ToMap() map[string]any {
	return map[string]any{
		"dec-order":                     s.DecOrder,
		"disable-const-dec-num-check":   s.DisableConstDecNumCheck,
		"disable-dec-num-check":         s.DisableDecNumCheck,
		"disable-dec-order-check":       s.DisableDecOrderCheck,
		"disable-init-func-first-check": s.DisableInitFuncFirstCheck,
		"disable-type-dec-num-check":    s.DisableTypeDecNumCheck,
		"disable-var-dec-num-check":     s.DisableVarDecNumCheck,
		"ignore-underscore-vars":        s.IgnoreUnderscoreVars,
	}
}

var _ types.SettingsConverter = DecorderSettings{}

// DepguardSettings is generated from golangci-lint's JSON Schema.
type DepguardSettings struct {
	Rules map[string]any `yaml:"rules"`
}

func (s DepguardSettings) ToMap() map[string]any {
	return map[string]any{
		"rules": s.Rules,
	}
}

var _ types.SettingsConverter = DepguardSettings{}

// DogsledSettings is generated from golangci-lint's JSON Schema.
type DogsledSettings struct {
	MaxBlankIdentifiers int `yaml:"max-blank-identifiers"`
}

func (s DogsledSettings) ToMap() map[string]any {
	return map[string]any{
		"max-blank-identifiers": s.MaxBlankIdentifiers,
	}
}

var _ types.SettingsConverter = DogsledSettings{}

// DuplSettings is generated from golangci-lint's JSON Schema.
type DuplSettings struct {
	Threshold int `yaml:"threshold"`
}

func (s DuplSettings) ToMap() map[string]any {
	return map[string]any{
		"threshold": s.Threshold,
	}
}

var _ types.SettingsConverter = DuplSettings{}

// DupwordSettings is generated from golangci-lint's JSON Schema.
type DupwordSettings struct {
	CommentsOnly bool     `yaml:"comments-only"`
	Ignore       []string `yaml:"ignore"`
	Keywords     []string `yaml:"keywords"`
}

func (s DupwordSettings) ToMap() map[string]any {
	return map[string]any{
		"comments-only": s.CommentsOnly,
		"ignore":        s.Ignore,
		"keywords":      s.Keywords,
	}
}

var _ types.SettingsConverter = DupwordSettings{}

// EmbeddedstructfieldcheckSettings is generated from golangci-lint's JSON Schema.
type EmbeddedstructfieldcheckSettings struct {
	EmptyLine   bool `yaml:"empty-line"`
	ForbidMutex bool `yaml:"forbid-mutex"`
}

func (s EmbeddedstructfieldcheckSettings) ToMap() map[string]any {
	return map[string]any{
		"empty-line":   s.EmptyLine,
		"forbid-mutex": s.ForbidMutex,
	}
}

var _ types.SettingsConverter = EmbeddedstructfieldcheckSettings{}

// ErrcheckSettings is generated from golangci-lint's JSON Schema.
type ErrcheckSettings struct {
	CheckBlank               bool     `yaml:"check-blank"`
	CheckTypeAssertions      bool     `yaml:"check-type-assertions"`
	DisableDefaultExclusions bool     `yaml:"disable-default-exclusions"`
	ExcludeFunctions         []string `yaml:"exclude-functions"`
	Verbose                  bool     `yaml:"verbose"`
}

func (s ErrcheckSettings) ToMap() map[string]any {
	return map[string]any{
		"check-blank":                s.CheckBlank,
		"check-type-assertions":      s.CheckTypeAssertions,
		"disable-default-exclusions": s.DisableDefaultExclusions,
		"exclude-functions":          s.ExcludeFunctions,
		"verbose":                    s.Verbose,
	}
}

var _ types.SettingsConverter = ErrcheckSettings{}

// ErrchkjsonSettings is generated from golangci-lint's JSON Schema.
type ErrchkjsonSettings struct {
	CheckErrorFreeEncoding bool `yaml:"check-error-free-encoding"`
	ReportNoExported       bool `yaml:"report-no-exported"`
}

func (s ErrchkjsonSettings) ToMap() map[string]any {
	return map[string]any{
		"check-error-free-encoding": s.CheckErrorFreeEncoding,
		"report-no-exported":        s.ReportNoExported,
	}
}

var _ types.SettingsConverter = ErrchkjsonSettings{}

// ErrorlintSettings is generated from golangci-lint's JSON Schema.
type ErrorlintSettings struct {
	AllowedErrors         []map[string]any `yaml:"allowed-errors"`
	AllowedErrorsWildcard []map[string]any `yaml:"allowed-errors-wildcard"`
	Asserts               bool             `yaml:"asserts"`
	Comparison            bool             `yaml:"comparison"`
	Errorf                bool             `yaml:"errorf"`
	ErrorfMulti           bool             `yaml:"errorf-multi"`
}

func (s ErrorlintSettings) ToMap() map[string]any {
	return map[string]any{
		"allowed-errors":          s.AllowedErrors,
		"allowed-errors-wildcard": s.AllowedErrorsWildcard,
		"asserts":                 s.Asserts,
		"comparison":              s.Comparison,
		"errorf":                  s.Errorf,
		"errorf-multi":            s.ErrorfMulti,
	}
}

var _ types.SettingsConverter = ErrorlintSettings{}

// ExhaustiveSettings is generated from golangci-lint's JSON Schema.
type ExhaustiveSettings struct {
	Check                      []string `yaml:"check"`
	DefaultCaseRequired        bool     `yaml:"default-case-required"`
	DefaultSignifiesExhaustive bool     `yaml:"default-signifies-exhaustive"`
	ExplicitExhaustiveMap      bool     `yaml:"explicit-exhaustive-map"`
	ExplicitExhaustiveSwitch   bool     `yaml:"explicit-exhaustive-switch"`
	IgnoreEnumMembers          string   `yaml:"ignore-enum-members"`
	IgnoreEnumTypes            string   `yaml:"ignore-enum-types"`
	PackageScopeOnly           bool     `yaml:"package-scope-only"`
}

func (s ExhaustiveSettings) ToMap() map[string]any {
	return map[string]any{
		"check":                        s.Check,
		"default-case-required":        s.DefaultCaseRequired,
		"default-signifies-exhaustive": s.DefaultSignifiesExhaustive,
		"explicit-exhaustive-map":      s.ExplicitExhaustiveMap,
		"explicit-exhaustive-switch":   s.ExplicitExhaustiveSwitch,
		"ignore-enum-members":          s.IgnoreEnumMembers,
		"ignore-enum-types":            s.IgnoreEnumTypes,
		"package-scope-only":           s.PackageScopeOnly,
	}
}

var _ types.SettingsConverter = ExhaustiveSettings{}

// ExhaustructSettings is generated from golangci-lint's JSON Schema.
type ExhaustructSettings struct {
	AllowEmpty             bool     `yaml:"allow-empty"`
	AllowEmptyDeclarations bool     `yaml:"allow-empty-declarations"`
	AllowEmptyReturns      bool     `yaml:"allow-empty-returns"`
	AllowEmptyRx           []string `yaml:"allow-empty-rx"`
	Exclude                []string `yaml:"exclude"`
	Include                []string `yaml:"include"`
}

func (s ExhaustructSettings) ToMap() map[string]any {
	return map[string]any{
		"allow-empty":              s.AllowEmpty,
		"allow-empty-declarations": s.AllowEmptyDeclarations,
		"allow-empty-returns":      s.AllowEmptyReturns,
		"allow-empty-rx":           s.AllowEmptyRx,
		"exclude":                  s.Exclude,
		"include":                  s.Include,
	}
}

var _ types.SettingsConverter = ExhaustructSettings{}

// FatcontextSettings is generated from golangci-lint's JSON Schema.
type FatcontextSettings struct {
	CheckStructPointers bool `yaml:"check-struct-pointers"`
}

func (s FatcontextSettings) ToMap() map[string]any {
	return map[string]any{
		"check-struct-pointers": s.CheckStructPointers,
	}
}

var _ types.SettingsConverter = FatcontextSettings{}

// ForbidigoSettings is generated from golangci-lint's JSON Schema.
type ForbidigoSettings struct {
	AnalyzeTypes         bool             `yaml:"analyze-types"`
	ExcludeGodocExamples bool             `yaml:"exclude-godoc-examples"`
	Forbid               []map[string]any `yaml:"forbid"`
}

func (s ForbidigoSettings) ToMap() map[string]any {
	return map[string]any{
		"analyze-types":          s.AnalyzeTypes,
		"exclude-godoc-examples": s.ExcludeGodocExamples,
		"forbid":                 s.Forbid,
	}
}

var _ types.SettingsConverter = ForbidigoSettings{}

// FuncorderSettings is generated from golangci-lint's JSON Schema.
type FuncorderSettings struct {
	Alphabetical bool `yaml:"alphabetical"`
	Constructor  bool `yaml:"constructor"`
	Function     bool `yaml:"function"`
	StructMethod bool `yaml:"struct-method"`
}

func (s FuncorderSettings) ToMap() map[string]any {
	return map[string]any{
		"alphabetical":  s.Alphabetical,
		"constructor":   s.Constructor,
		"function":      s.Function,
		"struct-method": s.StructMethod,
	}
}

var _ types.SettingsConverter = FuncorderSettings{}

// FunlenSettings is generated from golangci-lint's JSON Schema.
type FunlenSettings struct {
	IgnoreComments bool `yaml:"ignore-comments"`
	Lines          int  `yaml:"lines"`
	Statements     int  `yaml:"statements"`
}

func (s FunlenSettings) ToMap() map[string]any {
	return map[string]any{
		"ignore-comments": s.IgnoreComments,
		"lines":           s.Lines,
		"statements":      s.Statements,
	}
}

var _ types.SettingsConverter = FunlenSettings{}

// GinkgolinterSettings is generated from golangci-lint's JSON Schema.
type GinkgolinterSettings struct {
	AllowHavelenZero             bool `yaml:"allow-havelen-zero"`
	ForbidFocusContainer         bool `yaml:"forbid-focus-container"`
	ForbidSpecPollution          bool `yaml:"forbid-spec-pollution"`
	ForceAssertionDescription    bool `yaml:"force-assertion-description"`
	ForceExpectTo                bool `yaml:"force-expect-to"`
	ForceSucceed                 bool `yaml:"force-succeed"`
	ForceTonot                   bool `yaml:"force-tonot"`
	SuppressAsyncAssertion       bool `yaml:"suppress-async-assertion"`
	SuppressCompareAssertion     bool `yaml:"suppress-compare-assertion"`
	SuppressErrAssertion         bool `yaml:"suppress-err-assertion"`
	SuppressLenAssertion         bool `yaml:"suppress-len-assertion"`
	SuppressNilAssertion         bool `yaml:"suppress-nil-assertion"`
	SuppressTypeCompareAssertion bool `yaml:"suppress-type-compare-assertion"`
	ValidateAsyncIntervals       bool `yaml:"validate-async-intervals"`
}

func (s GinkgolinterSettings) ToMap() map[string]any {
	return map[string]any{
		"allow-havelen-zero":              s.AllowHavelenZero,
		"forbid-focus-container":          s.ForbidFocusContainer,
		"forbid-spec-pollution":           s.ForbidSpecPollution,
		"force-assertion-description":     s.ForceAssertionDescription,
		"force-expect-to":                 s.ForceExpectTo,
		"force-succeed":                   s.ForceSucceed,
		"force-tonot":                     s.ForceTonot,
		"suppress-async-assertion":        s.SuppressAsyncAssertion,
		"suppress-compare-assertion":      s.SuppressCompareAssertion,
		"suppress-err-assertion":          s.SuppressErrAssertion,
		"suppress-len-assertion":          s.SuppressLenAssertion,
		"suppress-nil-assertion":          s.SuppressNilAssertion,
		"suppress-type-compare-assertion": s.SuppressTypeCompareAssertion,
		"validate-async-intervals":        s.ValidateAsyncIntervals,
	}
}

var _ types.SettingsConverter = GinkgolinterSettings{}

// GochecksumtypeSettings is generated from golangci-lint's JSON Schema.
type GochecksumtypeSettings struct {
	DefaultSignifiesExhaustive bool `yaml:"default-signifies-exhaustive"`
	IncludeSharedInterfaces    bool `yaml:"include-shared-interfaces"`
}

func (s GochecksumtypeSettings) ToMap() map[string]any {
	return map[string]any{
		"default-signifies-exhaustive": s.DefaultSignifiesExhaustive,
		"include-shared-interfaces":    s.IncludeSharedInterfaces,
	}
}

var _ types.SettingsConverter = GochecksumtypeSettings{}

// GocognitSettings is generated from golangci-lint's JSON Schema.
type GocognitSettings struct {
	MinComplexity int `yaml:"min-complexity"`
}

func (s GocognitSettings) ToMap() map[string]any {
	return map[string]any{
		"min-complexity": s.MinComplexity,
	}
}

var _ types.SettingsConverter = GocognitSettings{}

// GoconstSettings is generated from golangci-lint's JSON Schema.
type GoconstSettings struct {
	EvalConstExpressions bool     `yaml:"eval-const-expressions"`
	FindDuplicates       bool     `yaml:"find-duplicates"`
	IgnoreCalls          bool     `yaml:"ignore-calls"`
	IgnoreFunctions      []string `yaml:"ignore-functions"`
	IgnoreStringValues   []string `yaml:"ignore-string-values"`
	IgnoreTests          bool     `yaml:"ignore-tests"`
	MatchConstant        bool     `yaml:"match-constant"`
	Max                  int      `yaml:"max"`
	Min                  int      `yaml:"min"`
	MinLen               int      `yaml:"min-len"`
	MinOccurrences       int      `yaml:"min-occurrences"`
	Numbers              bool     `yaml:"numbers"`
}

func (s GoconstSettings) ToMap() map[string]any {
	return map[string]any{
		"eval-const-expressions": s.EvalConstExpressions,
		"find-duplicates":        s.FindDuplicates,
		"ignore-calls":           s.IgnoreCalls,
		"ignore-functions":       s.IgnoreFunctions,
		"ignore-string-values":   s.IgnoreStringValues,
		"ignore-tests":           s.IgnoreTests,
		"match-constant":         s.MatchConstant,
		"max":                    s.Max,
		"min":                    s.Min,
		"min-len":                s.MinLen,
		"min-occurrences":        s.MinOccurrences,
		"numbers":                s.Numbers,
	}
}

var _ types.SettingsConverter = GoconstSettings{}

// GocriticSettings is generated from golangci-lint's JSON Schema.
type GocriticSettings struct {
	DisableAll     bool           `yaml:"disable-all"`
	DisabledChecks []any          `yaml:"disabled-checks"`
	DisabledTags   []any          `yaml:"disabled-tags"`
	EnableAll      bool           `yaml:"enable-all"`
	EnabledChecks  []any          `yaml:"enabled-checks"`
	EnabledTags    []any          `yaml:"enabled-tags"`
	Settings       map[string]any `yaml:"settings"`
}

func (s GocriticSettings) ToMap() map[string]any {
	return map[string]any{
		"disable-all":     s.DisableAll,
		"disabled-checks": s.DisabledChecks,
		"disabled-tags":   s.DisabledTags,
		"enable-all":      s.EnableAll,
		"enabled-checks":  s.EnabledChecks,
		"enabled-tags":    s.EnabledTags,
		"settings":        s.Settings,
	}
}

var _ types.SettingsConverter = GocriticSettings{}

// GocycloSettings is generated from golangci-lint's JSON Schema.
type GocycloSettings struct {
	MinComplexity int `yaml:"min-complexity"`
}

func (s GocycloSettings) ToMap() map[string]any {
	return map[string]any{
		"min-complexity": s.MinComplexity,
	}
}

var _ types.SettingsConverter = GocycloSettings{}

// GodoclintSettings is generated from golangci-lint's JSON Schema.
type GodoclintSettings struct {
	Default string         `yaml:"default"`
	Disable []any          `yaml:"disable"`
	Enable  []any          `yaml:"enable"`
	Options map[string]any `yaml:"options"`
}

func (s GodoclintSettings) ToMap() map[string]any {
	return map[string]any{
		"default": s.Default,
		"disable": s.Disable,
		"enable":  s.Enable,
		"options": s.Options,
	}
}

var _ types.SettingsConverter = GodoclintSettings{}

// GodotSettings is generated from golangci-lint's JSON Schema.
type GodotSettings struct {
	Capital  bool     `yaml:"capital"`
	CheckAll bool     `yaml:"check-all"`
	Exclude  []string `yaml:"exclude"`
	Period   bool     `yaml:"period"`
	Scope    any      `yaml:"scope"`
}

func (s GodotSettings) ToMap() map[string]any {
	return map[string]any{
		"capital":   s.Capital,
		"check-all": s.CheckAll,
		"exclude":   s.Exclude,
		"period":    s.Period,
		"scope":     s.Scope,
	}
}

var _ types.SettingsConverter = GodotSettings{}

// GodoxSettings is generated from golangci-lint's JSON Schema.
type GodoxSettings struct {
	Keywords []string `yaml:"keywords"`
}

func (s GodoxSettings) ToMap() map[string]any {
	return map[string]any{
		"keywords": s.Keywords,
	}
}

var _ types.SettingsConverter = GodoxSettings{}

// GoheaderSettings is generated from golangci-lint's JSON Schema.
type GoheaderSettings struct {
	Template     string         `yaml:"template"`
	TemplatePath string         `yaml:"template-path"`
	Values       map[string]any `yaml:"values"`
}

func (s GoheaderSettings) ToMap() map[string]any {
	return map[string]any{
		"template":      s.Template,
		"template-path": s.TemplatePath,
		"values":        s.Values,
	}
}

var _ types.SettingsConverter = GoheaderSettings{}

// GomoddirectivesSettings is generated from golangci-lint's JSON Schema.
type GomoddirectivesSettings struct {
	CheckModulePath           bool     `yaml:"check-module-path"`
	ExcludeForbidden          bool     `yaml:"exclude-forbidden"`
	GoDebugForbidden          bool     `yaml:"go-debug-forbidden"`
	GoVersionPattern          string   `yaml:"go-version-pattern"`
	IgnoreForbidden           bool     `yaml:"ignore-forbidden"`
	ReplaceAllowList          []string `yaml:"replace-allow-list"`
	ReplaceLocal              bool     `yaml:"replace-local"`
	RetractAllowNoExplanation bool     `yaml:"retract-allow-no-explanation"`
	ToolForbidden             bool     `yaml:"tool-forbidden"`
	ToolchainForbidden        bool     `yaml:"toolchain-forbidden"`
	ToolchainPattern          string   `yaml:"toolchain-pattern"`
}

func (s GomoddirectivesSettings) ToMap() map[string]any {
	return map[string]any{
		"check-module-path":            s.CheckModulePath,
		"exclude-forbidden":            s.ExcludeForbidden,
		"go-debug-forbidden":           s.GoDebugForbidden,
		"go-version-pattern":           s.GoVersionPattern,
		"ignore-forbidden":             s.IgnoreForbidden,
		"replace-allow-list":           s.ReplaceAllowList,
		"replace-local":                s.ReplaceLocal,
		"retract-allow-no-explanation": s.RetractAllowNoExplanation,
		"tool-forbidden":               s.ToolForbidden,
		"toolchain-forbidden":          s.ToolchainForbidden,
		"toolchain-pattern":            s.ToolchainPattern,
	}
}

var _ types.SettingsConverter = GomoddirectivesSettings{}

// GomodguardSettings is generated from golangci-lint's JSON Schema.
type GomodguardSettings struct {
	Allowed map[string]any `yaml:"allowed"`
	Blocked map[string]any `yaml:"blocked"`
}

func (s GomodguardSettings) ToMap() map[string]any {
	return map[string]any{
		"allowed": s.Allowed,
		"blocked": s.Blocked,
	}
}

var _ types.SettingsConverter = GomodguardSettings{}

// GomodguardV2Settings is generated from golangci-lint's JSON Schema.
type GomodguardV2Settings struct {
	Allowed                []map[string]any `yaml:"allowed"`
	Blocked                []map[string]any `yaml:"blocked"`
	LocalReplaceDirectives bool             `yaml:"local-replace-directives"`
}

func (s GomodguardV2Settings) ToMap() map[string]any {
	return map[string]any{
		"allowed":                  s.Allowed,
		"blocked":                  s.Blocked,
		"local-replace-directives": s.LocalReplaceDirectives,
	}
}

var _ types.SettingsConverter = GomodguardV2Settings{}

// GosecSettings is generated from golangci-lint's JSON Schema.
type GosecSettings struct {
	Concurrency int            `yaml:"concurrency"`
	Confidence  string         `yaml:"confidence"`
	Config      map[string]any `yaml:"config"`
	Excludes    []any          `yaml:"excludes"`
	Includes    []any          `yaml:"includes"`
	Severity    string         `yaml:"severity"`
}

func (s GosecSettings) ToMap() map[string]any {
	return map[string]any{
		"concurrency": s.Concurrency,
		"confidence":  s.Confidence,
		"config":      s.Config,
		"excludes":    s.Excludes,
		"includes":    s.Includes,
		"severity":    s.Severity,
	}
}

var _ types.SettingsConverter = GosecSettings{}

// GosmopolitanSettings is generated from golangci-lint's JSON Schema.
type GosmopolitanSettings struct {
	AllowTimeLocal  bool     `yaml:"allow-time-local"`
	EscapeHatches   []string `yaml:"escape-hatches"`
	WatchForScripts []string `yaml:"watch-for-scripts"`
}

func (s GosmopolitanSettings) ToMap() map[string]any {
	return map[string]any{
		"allow-time-local":  s.AllowTimeLocal,
		"escape-hatches":    s.EscapeHatches,
		"watch-for-scripts": s.WatchForScripts,
	}
}

var _ types.SettingsConverter = GosmopolitanSettings{}

// GovetSettings is generated from golangci-lint's JSON Schema.
type GovetSettings struct {
	Disable    []any          `yaml:"disable"`
	DisableAll bool           `yaml:"disable-all"`
	Enable     []any          `yaml:"enable"`
	EnableAll  bool           `yaml:"enable-all"`
	Settings   map[string]any `yaml:"settings"`
}

func (s GovetSettings) ToMap() map[string]any {
	return map[string]any{
		"disable":     s.Disable,
		"disable-all": s.DisableAll,
		"enable":      s.Enable,
		"enable-all":  s.EnableAll,
		"settings":    s.Settings,
	}
}

var _ types.SettingsConverter = GovetSettings{}

// GrouperSettings is generated from golangci-lint's JSON Schema.
type GrouperSettings struct {
	ConstRequireGrouping      bool `yaml:"const-require-grouping"`
	ConstRequireSingleConst   bool `yaml:"const-require-single-const"`
	ImportRequireGrouping     bool `yaml:"import-require-grouping"`
	ImportRequireSingleImport bool `yaml:"import-require-single-import"`
	TypeRequireGrouping       bool `yaml:"type-require-grouping"`
	TypeRequireSingleType     bool `yaml:"type-require-single-type"`
	VarRequireGrouping        bool `yaml:"var-require-grouping"`
	VarRequireSingleVar       bool `yaml:"var-require-single-var"`
}

func (s GrouperSettings) ToMap() map[string]any {
	return map[string]any{
		"const-require-grouping":       s.ConstRequireGrouping,
		"const-require-single-const":   s.ConstRequireSingleConst,
		"import-require-grouping":      s.ImportRequireGrouping,
		"import-require-single-import": s.ImportRequireSingleImport,
		"type-require-grouping":        s.TypeRequireGrouping,
		"type-require-single-type":     s.TypeRequireSingleType,
		"var-require-grouping":         s.VarRequireGrouping,
		"var-require-single-var":       s.VarRequireSingleVar,
	}
}

var _ types.SettingsConverter = GrouperSettings{}

// IfaceSettings is generated from golangci-lint's JSON Schema.
type IfaceSettings struct {
	Enable   []any          `yaml:"enable"`
	Settings map[string]any `yaml:"settings"`
}

func (s IfaceSettings) ToMap() map[string]any {
	return map[string]any{
		"enable":   s.Enable,
		"settings": s.Settings,
	}
}

var _ types.SettingsConverter = IfaceSettings{}

// ImportasSettings is generated from golangci-lint's JSON Schema.
type ImportasSettings struct {
	Alias          []map[string]any `yaml:"alias"`
	NoExtraAliases bool             `yaml:"no-extra-aliases"`
	NoUnaliased    bool             `yaml:"no-unaliased"`
}

func (s ImportasSettings) ToMap() map[string]any {
	return map[string]any{
		"alias":            s.Alias,
		"no-extra-aliases": s.NoExtraAliases,
		"no-unaliased":     s.NoUnaliased,
	}
}

var _ types.SettingsConverter = ImportasSettings{}

// InamedparamSettings is generated from golangci-lint's JSON Schema.
type InamedparamSettings struct {
	SkipSingleParam bool `yaml:"skip-single-param"`
}

func (s InamedparamSettings) ToMap() map[string]any {
	return map[string]any{
		"skip-single-param": s.SkipSingleParam,
	}
}

var _ types.SettingsConverter = InamedparamSettings{}

// IneffassignSettings is generated from golangci-lint's JSON Schema.
type IneffassignSettings struct {
	CheckEscapingErrors bool `yaml:"check-escaping-errors"`
}

func (s IneffassignSettings) ToMap() map[string]any {
	return map[string]any{
		"check-escaping-errors": s.CheckEscapingErrors,
	}
}

var _ types.SettingsConverter = IneffassignSettings{}

// InterfacebloatSettings is generated from golangci-lint's JSON Schema.
type InterfacebloatSettings struct {
	Max int `yaml:"max"`
}

func (s InterfacebloatSettings) ToMap() map[string]any {
	return map[string]any{
		"max": s.Max,
	}
}

var _ types.SettingsConverter = InterfacebloatSettings{}

// IotamixingSettings is generated from golangci-lint's JSON Schema.
type IotamixingSettings struct {
	ReportIndividual bool `yaml:"report-individual"`
}

func (s IotamixingSettings) ToMap() map[string]any {
	return map[string]any{
		"report-individual": s.ReportIndividual,
	}
}

var _ types.SettingsConverter = IotamixingSettings{}

// IreturnSettings is generated from golangci-lint's JSON Schema.
type IreturnSettings struct {
	Allow  []any `yaml:"allow"`
	Reject []any `yaml:"reject"`
}

func (s IreturnSettings) ToMap() map[string]any {
	return map[string]any{
		"allow":  s.Allow,
		"reject": s.Reject,
	}
}

var _ types.SettingsConverter = IreturnSettings{}

// LllSettings is generated from golangci-lint's JSON Schema.
type LllSettings struct {
	LineLength int `yaml:"line-length"`
	TabWidth   int `yaml:"tab-width"`
}

func (s LllSettings) ToMap() map[string]any {
	return map[string]any{
		"line-length": s.LineLength,
		"tab-width":   s.TabWidth,
	}
}

var _ types.SettingsConverter = LllSettings{}

// LoggercheckSettings is generated from golangci-lint's JSON Schema.
type LoggercheckSettings struct {
	Kitlog           bool     `yaml:"kitlog"`
	Klog             bool     `yaml:"klog"`
	Logr             bool     `yaml:"logr"`
	NoPrintfLike     bool     `yaml:"no-printf-like"`
	RequireStringKey bool     `yaml:"require-string-key"`
	Rules            []string `yaml:"rules"`
	Slog             bool     `yaml:"slog"`
	Zap              bool     `yaml:"zap"`
}

func (s LoggercheckSettings) ToMap() map[string]any {
	return map[string]any{
		"kitlog":             s.Kitlog,
		"klog":               s.Klog,
		"logr":               s.Logr,
		"no-printf-like":     s.NoPrintfLike,
		"require-string-key": s.RequireStringKey,
		"rules":              s.Rules,
		"slog":               s.Slog,
		"zap":                s.Zap,
	}
}

var _ types.SettingsConverter = LoggercheckSettings{}

// MaintidxSettings is generated from golangci-lint's JSON Schema.
type MaintidxSettings struct {
	Under float64 `yaml:"under"`
}

func (s MaintidxSettings) ToMap() map[string]any {
	return map[string]any{
		"under": s.Under,
	}
}

var _ types.SettingsConverter = MaintidxSettings{}

// MakezeroSettings is generated from golangci-lint's JSON Schema.
type MakezeroSettings struct {
	Always bool `yaml:"always"`
}

func (s MakezeroSettings) ToMap() map[string]any {
	return map[string]any{
		"always": s.Always,
	}
}

var _ types.SettingsConverter = MakezeroSettings{}

// MisspellSettings is generated from golangci-lint's JSON Schema.
type MisspellSettings struct {
	ExtraWords  []map[string]any `yaml:"extra-words"`
	IgnoreRules []string         `yaml:"ignore-rules"`
	Locale      any              `yaml:"locale"`
	Mode        any              `yaml:"mode"`
}

func (s MisspellSettings) ToMap() map[string]any {
	return map[string]any{
		"extra-words":  s.ExtraWords,
		"ignore-rules": s.IgnoreRules,
		"locale":       s.Locale,
		"mode":         s.Mode,
	}
}

var _ types.SettingsConverter = MisspellSettings{}

// MndSettings is generated from golangci-lint's JSON Schema.
type MndSettings struct {
	Checks           []any    `yaml:"checks"`
	IgnoredFiles     []string `yaml:"ignored-files"`
	IgnoredFunctions []string `yaml:"ignored-functions"`
	IgnoredNumbers   []string `yaml:"ignored-numbers"`
}

func (s MndSettings) ToMap() map[string]any {
	return map[string]any{
		"checks":            s.Checks,
		"ignored-files":     s.IgnoredFiles,
		"ignored-functions": s.IgnoredFunctions,
		"ignored-numbers":   s.IgnoredNumbers,
	}
}

var _ types.SettingsConverter = MndSettings{}

// ModernizeSettings is generated from golangci-lint's JSON Schema.
type ModernizeSettings struct {
	Disable []any `yaml:"disable"`
}

func (s ModernizeSettings) ToMap() map[string]any {
	return map[string]any{
		"disable": s.Disable,
	}
}

var _ types.SettingsConverter = ModernizeSettings{}

// MusttagSettings is generated from golangci-lint's JSON Schema.
type MusttagSettings struct {
	Functions []map[string]any `yaml:"functions"`
}

func (s MusttagSettings) ToMap() map[string]any {
	return map[string]any{
		"functions": s.Functions,
	}
}

var _ types.SettingsConverter = MusttagSettings{}

// NakedretSettings is generated from golangci-lint's JSON Schema.
type NakedretSettings struct {
	MaxFuncLines int `yaml:"max-func-lines"`
}

func (s NakedretSettings) ToMap() map[string]any {
	return map[string]any{
		"max-func-lines": s.MaxFuncLines,
	}
}

var _ types.SettingsConverter = NakedretSettings{}

// NestifSettings is generated from golangci-lint's JSON Schema.
type NestifSettings struct {
	MinComplexity int `yaml:"min-complexity"`
}

func (s NestifSettings) ToMap() map[string]any {
	return map[string]any{
		"min-complexity": s.MinComplexity,
	}
}

var _ types.SettingsConverter = NestifSettings{}

// NilnilSettings is generated from golangci-lint's JSON Schema.
type NilnilSettings struct {
	CheckedTypes   []any `yaml:"checked-types"`
	DetectOpposite bool  `yaml:"detect-opposite"`
	OnlyTwo        bool  `yaml:"only-two"`
}

func (s NilnilSettings) ToMap() map[string]any {
	return map[string]any{
		"checked-types":   s.CheckedTypes,
		"detect-opposite": s.DetectOpposite,
		"only-two":        s.OnlyTwo,
	}
}

var _ types.SettingsConverter = NilnilSettings{}

// NlreturnSettings is generated from golangci-lint's JSON Schema.
type NlreturnSettings struct {
	BlockSize float64 `yaml:"block-size"`
}

func (s NlreturnSettings) ToMap() map[string]any {
	return map[string]any{
		"block-size": s.BlockSize,
	}
}

var _ types.SettingsConverter = NlreturnSettings{}

// NolintlintSettings is generated from golangci-lint's JSON Schema.
type NolintlintSettings struct {
	AllowNoExplanation []any `yaml:"allow-no-explanation"`
	AllowUnused        bool  `yaml:"allow-unused"`
	RequireExplanation bool  `yaml:"require-explanation"`
	RequireSpecific    bool  `yaml:"require-specific"`
}

func (s NolintlintSettings) ToMap() map[string]any {
	return map[string]any{
		"allow-no-explanation": s.AllowNoExplanation,
		"allow-unused":         s.AllowUnused,
		"require-explanation":  s.RequireExplanation,
		"require-specific":     s.RequireSpecific,
	}
}

var _ types.SettingsConverter = NolintlintSettings{}

// NonamedreturnsSettings is generated from golangci-lint's JSON Schema.
type NonamedreturnsSettings struct {
	ReportErrorInDefer bool `yaml:"report-error-in-defer"`
}

func (s NonamedreturnsSettings) ToMap() map[string]any {
	return map[string]any{
		"report-error-in-defer": s.ReportErrorInDefer,
	}
}

var _ types.SettingsConverter = NonamedreturnsSettings{}

// ParalleltestSettings is generated from golangci-lint's JSON Schema.
type ParalleltestSettings struct {
	CheckCleanup          bool `yaml:"check-cleanup"`
	IgnoreMissing         bool `yaml:"ignore-missing"`
	IgnoreMissingSubtests bool `yaml:"ignore-missing-subtests"`
}

func (s ParalleltestSettings) ToMap() map[string]any {
	return map[string]any{
		"check-cleanup":           s.CheckCleanup,
		"ignore-missing":          s.IgnoreMissing,
		"ignore-missing-subtests": s.IgnoreMissingSubtests,
	}
}

var _ types.SettingsConverter = ParalleltestSettings{}

// PerfsprintSettings is generated from golangci-lint's JSON Schema.
type PerfsprintSettings struct {
	BoolFormat    bool `yaml:"bool-format"`
	ConcatLoop    bool `yaml:"concat-loop"`
	ErrError      bool `yaml:"err-error"`
	ErrorFormat   bool `yaml:"error-format"`
	Errorf        bool `yaml:"errorf"`
	HexFormat     bool `yaml:"hex-format"`
	IntConversion bool `yaml:"int-conversion"`
	IntegerFormat bool `yaml:"integer-format"`
	LoopOtherOps  bool `yaml:"loop-other-ops"`
	Sprintf1      bool `yaml:"sprintf1"`
	Strconcat     bool `yaml:"strconcat"`
	StringFormat  bool `yaml:"string-format"`
}

func (s PerfsprintSettings) ToMap() map[string]any {
	return map[string]any{
		"bool-format":    s.BoolFormat,
		"concat-loop":    s.ConcatLoop,
		"err-error":      s.ErrError,
		"error-format":   s.ErrorFormat,
		"errorf":         s.Errorf,
		"hex-format":     s.HexFormat,
		"int-conversion": s.IntConversion,
		"integer-format": s.IntegerFormat,
		"loop-other-ops": s.LoopOtherOps,
		"sprintf1":       s.Sprintf1,
		"strconcat":      s.Strconcat,
		"string-format":  s.StringFormat,
	}
}

var _ types.SettingsConverter = PerfsprintSettings{}

// PreallocSettings is generated from golangci-lint's JSON Schema.
type PreallocSettings struct {
	ForLoops   bool `yaml:"for-loops"`
	RangeLoops bool `yaml:"range-loops"`
	Simple     bool `yaml:"simple"`
}

func (s PreallocSettings) ToMap() map[string]any {
	return map[string]any{
		"for-loops":   s.ForLoops,
		"range-loops": s.RangeLoops,
		"simple":      s.Simple,
	}
}

var _ types.SettingsConverter = PreallocSettings{}

// PredeclaredSettings is generated from golangci-lint's JSON Schema.
type PredeclaredSettings struct {
	Ignore        []string `yaml:"ignore"`
	QualifiedName bool     `yaml:"qualified-name"`
}

func (s PredeclaredSettings) ToMap() map[string]any {
	return map[string]any{
		"ignore":         s.Ignore,
		"qualified-name": s.QualifiedName,
	}
}

var _ types.SettingsConverter = PredeclaredSettings{}

// PromlinterSettings is generated from golangci-lint's JSON Schema.
type PromlinterSettings struct {
	DisabledLinters []any `yaml:"disabled-linters"`
	Strict          any   `yaml:"strict"`
}

func (s PromlinterSettings) ToMap() map[string]any {
	return map[string]any{
		"disabled-linters": s.DisabledLinters,
		"strict":           s.Strict,
	}
}

var _ types.SettingsConverter = PromlinterSettings{}

// ProtogetterSettings is generated from golangci-lint's JSON Schema.
type ProtogetterSettings struct {
	ReplaceFirstArgInAppend bool     `yaml:"replace-first-arg-in-append"`
	SkipAnyGenerated        bool     `yaml:"skip-any-generated"`
	SkipFiles               []string `yaml:"skip-files"`
	SkipGeneratedBy         []string `yaml:"skip-generated-by"`
}

func (s ProtogetterSettings) ToMap() map[string]any {
	return map[string]any{
		"replace-first-arg-in-append": s.ReplaceFirstArgInAppend,
		"skip-any-generated":          s.SkipAnyGenerated,
		"skip-files":                  s.SkipFiles,
		"skip-generated-by":           s.SkipGeneratedBy,
	}
}

var _ types.SettingsConverter = ProtogetterSettings{}

// ReassignSettings is generated from golangci-lint's JSON Schema.
type ReassignSettings struct {
	Patterns []string `yaml:"patterns"`
}

func (s ReassignSettings) ToMap() map[string]any {
	return map[string]any{
		"patterns": s.Patterns,
	}
}

var _ types.SettingsConverter = ReassignSettings{}

// RecvcheckSettings is generated from golangci-lint's JSON Schema.
type RecvcheckSettings struct {
	DisableBuiltin bool     `yaml:"disable-builtin"`
	Exclusions     []string `yaml:"exclusions"`
}

func (s RecvcheckSettings) ToMap() map[string]any {
	return map[string]any{
		"disable-builtin": s.DisableBuiltin,
		"exclusions":      s.Exclusions,
	}
}

var _ types.SettingsConverter = RecvcheckSettings{}

// ReviveSettings is generated from golangci-lint's JSON Schema.
type ReviveSettings struct {
	Confidence         float64          `yaml:"confidence"`
	Directives         []map[string]any `yaml:"directives"`
	EnableAllRules     bool             `yaml:"enable-all-rules"`
	EnableDefaultRules bool             `yaml:"enable-default-rules"`
	MaxOpenFiles       int              `yaml:"max-open-files"`
	Rules              []map[string]any `yaml:"rules"`
	Severity           string           `yaml:"severity"`
}

func (s ReviveSettings) ToMap() map[string]any {
	return map[string]any{
		"confidence":           s.Confidence,
		"directives":           s.Directives,
		"enable-all-rules":     s.EnableAllRules,
		"enable-default-rules": s.EnableDefaultRules,
		"max-open-files":       s.MaxOpenFiles,
		"rules":                s.Rules,
		"severity":             s.Severity,
	}
}

var _ types.SettingsConverter = ReviveSettings{}

// RowserrcheckSettings is generated from golangci-lint's JSON Schema.
type RowserrcheckSettings struct {
	Packages []string `yaml:"packages"`
}

func (s RowserrcheckSettings) ToMap() map[string]any {
	return map[string]any{
		"packages": s.Packages,
	}
}

var _ types.SettingsConverter = RowserrcheckSettings{}

// SloglintSettings is generated from golangci-lint's JSON Schema.
type SloglintSettings struct {
	AllowedKeys    []string `yaml:"allowed-keys"`
	ArgsOnSepLines bool     `yaml:"args-on-sep-lines"`
	AttrOnly       bool     `yaml:"attr-only"`
	Context        any      `yaml:"context"`
	CustomFuncs    []any    `yaml:"custom-funcs"`
	ForbiddenKeys  []string `yaml:"forbidden-keys"`
	KeyNamingCase  any      `yaml:"key-naming-case"`
	KvOnly         bool     `yaml:"kv-only"`
	MsgStyle       any      `yaml:"msg-style"`
	NoGlobal       any      `yaml:"no-global"`
	NoMixedArgs    bool     `yaml:"no-mixed-args"`
	NoRawKeys      bool     `yaml:"no-raw-keys"`
	StaticMsg      bool     `yaml:"static-msg"`
}

func (s SloglintSettings) ToMap() map[string]any {
	return map[string]any{
		"allowed-keys":      s.AllowedKeys,
		"args-on-sep-lines": s.ArgsOnSepLines,
		"attr-only":         s.AttrOnly,
		"context":           s.Context,
		"custom-funcs":      s.CustomFuncs,
		"forbidden-keys":    s.ForbiddenKeys,
		"key-naming-case":   s.KeyNamingCase,
		"kv-only":           s.KvOnly,
		"msg-style":         s.MsgStyle,
		"no-global":         s.NoGlobal,
		"no-mixed-args":     s.NoMixedArgs,
		"no-raw-keys":       s.NoRawKeys,
		"static-msg":        s.StaticMsg,
	}
}

var _ types.SettingsConverter = SloglintSettings{}

// SpancheckSettings is generated from golangci-lint's JSON Schema.
type SpancheckSettings struct {
	Checks                   []any    `yaml:"checks"`
	ExtraStartSpanSignatures []string `yaml:"extra-start-span-signatures"`
	IgnoreCheckSignatures    []string `yaml:"ignore-check-signatures"`
}

func (s SpancheckSettings) ToMap() map[string]any {
	return map[string]any{
		"checks":                      s.Checks,
		"extra-start-span-signatures": s.ExtraStartSpanSignatures,
		"ignore-check-signatures":     s.IgnoreCheckSignatures,
	}
}

var _ types.SettingsConverter = SpancheckSettings{}

// StaticcheckSettings is generated from golangci-lint's JSON Schema.
type StaticcheckSettings struct {
	Checks                  []any    `yaml:"checks"`
	DotImportWhitelist      []string `yaml:"dot-import-whitelist"`
	HttpStatusCodeWhitelist []any    `yaml:"http-status-code-whitelist"`
	Initialisms             []string `yaml:"initialisms"`
}

func (s StaticcheckSettings) ToMap() map[string]any {
	return map[string]any{
		"checks":                     s.Checks,
		"dot-import-whitelist":       s.DotImportWhitelist,
		"http-status-code-whitelist": s.HttpStatusCodeWhitelist,
		"initialisms":                s.Initialisms,
	}
}

var _ types.SettingsConverter = StaticcheckSettings{}

// TagalignSettings is generated from golangci-lint's JSON Schema.
type TagalignSettings struct {
	Align  bool     `yaml:"align"`
	Order  []string `yaml:"order"`
	Sort   bool     `yaml:"sort"`
	Strict bool     `yaml:"strict"`
}

func (s TagalignSettings) ToMap() map[string]any {
	return map[string]any{
		"align":  s.Align,
		"order":  s.Order,
		"sort":   s.Sort,
		"strict": s.Strict,
	}
}

var _ types.SettingsConverter = TagalignSettings{}

// TagliatelleSettings is generated from golangci-lint's JSON Schema.
type TagliatelleSettings struct {
	Case map[string]any `yaml:"case"`
}

func (s TagliatelleSettings) ToMap() map[string]any {
	return map[string]any{
		"case": s.Case,
	}
}

var _ types.SettingsConverter = TagliatelleSettings{}

// TestifylintSettings is generated from golangci-lint's JSON Schema.
type TestifylintSettings struct {
	BoolCompare          map[string]any `yaml:"bool-compare"`
	Disable              []any          `yaml:"disable"`
	DisableAll           bool           `yaml:"disable-all"`
	Enable               []any          `yaml:"enable"`
	EnableAll            bool           `yaml:"enable-all"`
	ExpectedActual       map[string]any `yaml:"expected-actual"`
	Formatter            map[string]any `yaml:"formatter"`
	GoRequire            map[string]any `yaml:"go-require"`
	RequireError         map[string]any `yaml:"require-error"`
	SuiteExtraAssertCall map[string]any `yaml:"suite-extra-assert-call"`
}

func (s TestifylintSettings) ToMap() map[string]any {
	return map[string]any{
		"bool-compare":            s.BoolCompare,
		"disable":                 s.Disable,
		"disable-all":             s.DisableAll,
		"enable":                  s.Enable,
		"enable-all":              s.EnableAll,
		"expected-actual":         s.ExpectedActual,
		"formatter":               s.Formatter,
		"go-require":              s.GoRequire,
		"require-error":           s.RequireError,
		"suite-extra-assert-call": s.SuiteExtraAssertCall,
	}
}

var _ types.SettingsConverter = TestifylintSettings{}

// TestpackageSettings is generated from golangci-lint's JSON Schema.
type TestpackageSettings struct {
	AllowPackages []string `yaml:"allow-packages"`
	SkipRegexp    string   `yaml:"skip-regexp"`
}

func (s TestpackageSettings) ToMap() map[string]any {
	return map[string]any{
		"allow-packages": s.AllowPackages,
		"skip-regexp":    s.SkipRegexp,
	}
}

var _ types.SettingsConverter = TestpackageSettings{}

// ThelperSettings is generated from golangci-lint's JSON Schema.
type ThelperSettings struct {
	Benchmark map[string]any `yaml:"benchmark"`
	Fuzz      map[string]any `yaml:"fuzz"`
	Tb        map[string]any `yaml:"tb"`
	Test      map[string]any `yaml:"test"`
}

func (s ThelperSettings) ToMap() map[string]any {
	return map[string]any{
		"benchmark": s.Benchmark,
		"fuzz":      s.Fuzz,
		"tb":        s.Tb,
		"test":      s.Test,
	}
}

var _ types.SettingsConverter = ThelperSettings{}

// UnconvertSettings is generated from golangci-lint's JSON Schema.
type UnconvertSettings struct {
	FastMath bool `yaml:"fast-math"`
	Safe     bool `yaml:"safe"`
}

func (s UnconvertSettings) ToMap() map[string]any {
	return map[string]any{
		"fast-math": s.FastMath,
		"safe":      s.Safe,
	}
}

var _ types.SettingsConverter = UnconvertSettings{}

// UnparamSettings is generated from golangci-lint's JSON Schema.
type UnparamSettings struct {
	CheckExported bool `yaml:"check-exported"`
}

func (s UnparamSettings) ToMap() map[string]any {
	return map[string]any{
		"check-exported": s.CheckExported,
	}
}

var _ types.SettingsConverter = UnparamSettings{}

// UnqueryvetSettings is generated from golangci-lint's JSON Schema.
type UnqueryvetSettings struct {
	Allow                []string         `yaml:"allow"`
	AllowedPatterns      []string         `yaml:"allowed-patterns"`
	CheckAliasedWildcard bool             `yaml:"check-aliased-wildcard"`
	CheckFormatStrings   bool             `yaml:"check-format-strings"`
	CheckN1              bool             `yaml:"check-n1"`
	CheckSqlBuilders     bool             `yaml:"check-sql-builders"`
	CheckSqlInjection    bool             `yaml:"check-sql-injection"`
	CheckStringBuilder   bool             `yaml:"check-string-builder"`
	CheckStringConcat    bool             `yaml:"check-string-concat"`
	CheckSubqueries      bool             `yaml:"check-subqueries"`
	CheckTxLeaks         bool             `yaml:"check-tx-leaks"`
	CustomRules          []map[string]any `yaml:"custom-rules"`
	IgnoredFunctions     []string         `yaml:"ignored-functions"`
	SqlBuilders          map[string]any   `yaml:"sql-builders"`
}

func (s UnqueryvetSettings) ToMap() map[string]any {
	return map[string]any{
		"allow":                  s.Allow,
		"allowed-patterns":       s.AllowedPatterns,
		"check-aliased-wildcard": s.CheckAliasedWildcard,
		"check-format-strings":   s.CheckFormatStrings,
		"check-n1":               s.CheckN1,
		"check-sql-builders":     s.CheckSqlBuilders,
		"check-sql-injection":    s.CheckSqlInjection,
		"check-string-builder":   s.CheckStringBuilder,
		"check-string-concat":    s.CheckStringConcat,
		"check-subqueries":       s.CheckSubqueries,
		"check-tx-leaks":         s.CheckTxLeaks,
		"custom-rules":           s.CustomRules,
		"ignored-functions":      s.IgnoredFunctions,
		"sql-builders":           s.SqlBuilders,
	}
}

var _ types.SettingsConverter = UnqueryvetSettings{}

// UnusedSettings is generated from golangci-lint's JSON Schema.
type UnusedSettings struct {
	ExportedFieldsAreUsed  bool `yaml:"exported-fields-are-used"`
	FieldWritesAreUses     bool `yaml:"field-writes-are-uses"`
	GeneratedIsUsed        bool `yaml:"generated-is-used"`
	LocalVariablesAreUsed  bool `yaml:"local-variables-are-used"`
	ParametersAreUsed      bool `yaml:"parameters-are-used"`
	PostStatementsAreReads bool `yaml:"post-statements-are-reads"`
}

func (s UnusedSettings) ToMap() map[string]any {
	return map[string]any{
		"exported-fields-are-used":  s.ExportedFieldsAreUsed,
		"field-writes-are-uses":     s.FieldWritesAreUses,
		"generated-is-used":         s.GeneratedIsUsed,
		"local-variables-are-used":  s.LocalVariablesAreUsed,
		"parameters-are-used":       s.ParametersAreUsed,
		"post-statements-are-reads": s.PostStatementsAreReads,
	}
}

var _ types.SettingsConverter = UnusedSettings{}

// UsestdlibvarsSettings is generated from golangci-lint's JSON Schema.
type UsestdlibvarsSettings struct {
	ConstantKind       bool `yaml:"constant-kind"`
	CryptoHash         bool `yaml:"crypto-hash"`
	DefaultRpcPath     bool `yaml:"default-rpc-path"`
	HttpMethod         bool `yaml:"http-method"`
	HttpStatusCode     bool `yaml:"http-status-code"`
	SqlIsolationLevel  bool `yaml:"sql-isolation-level"`
	TimeDateMonth      bool `yaml:"time-date-month"`
	TimeLayout         bool `yaml:"time-layout"`
	TimeMonth          bool `yaml:"time-month"`
	TimeWeekday        bool `yaml:"time-weekday"`
	TlsSignatureScheme bool `yaml:"tls-signature-scheme"`
}

func (s UsestdlibvarsSettings) ToMap() map[string]any {
	return map[string]any{
		"constant-kind":        s.ConstantKind,
		"crypto-hash":          s.CryptoHash,
		"default-rpc-path":     s.DefaultRpcPath,
		"http-method":          s.HttpMethod,
		"http-status-code":     s.HttpStatusCode,
		"sql-isolation-level":  s.SqlIsolationLevel,
		"time-date-month":      s.TimeDateMonth,
		"time-layout":          s.TimeLayout,
		"time-month":           s.TimeMonth,
		"time-weekday":         s.TimeWeekday,
		"tls-signature-scheme": s.TlsSignatureScheme,
	}
}

var _ types.SettingsConverter = UsestdlibvarsSettings{}

// UsetestingSettings is generated from golangci-lint's JSON Schema.
type UsetestingSettings struct {
	ContextBackground bool `yaml:"context-background"`
	ContextTodo       bool `yaml:"context-todo"`
	OsChdir           bool `yaml:"os-chdir"`
	OsCreateTemp      bool `yaml:"os-create-temp"`
	OsMkdirTemp       bool `yaml:"os-mkdir-temp"`
	OsSetenv          bool `yaml:"os-setenv"`
	OsTempDir         bool `yaml:"os-temp-dir"`
}

func (s UsetestingSettings) ToMap() map[string]any {
	return map[string]any{
		"context-background": s.ContextBackground,
		"context-todo":       s.ContextTodo,
		"os-chdir":           s.OsChdir,
		"os-create-temp":     s.OsCreateTemp,
		"os-mkdir-temp":      s.OsMkdirTemp,
		"os-setenv":          s.OsSetenv,
		"os-temp-dir":        s.OsTempDir,
	}
}

var _ types.SettingsConverter = UsetestingSettings{}

// VarnamelenSettings is generated from golangci-lint's JSON Schema.
type VarnamelenSettings struct {
	CheckReceiver      bool     `yaml:"check-receiver"`
	CheckReturn        bool     `yaml:"check-return"`
	CheckTypeParam     bool     `yaml:"check-type-param"`
	IgnoreChanRecvOk   bool     `yaml:"ignore-chan-recv-ok"`
	IgnoreDecls        []string `yaml:"ignore-decls"`
	IgnoreMapIndexOk   bool     `yaml:"ignore-map-index-ok"`
	IgnoreNames        []string `yaml:"ignore-names"`
	IgnoreTypeAssertOk bool     `yaml:"ignore-type-assert-ok"`
	MaxDistance        int      `yaml:"max-distance"`
	MinNameLength      int      `yaml:"min-name-length"`
}

func (s VarnamelenSettings) ToMap() map[string]any {
	return map[string]any{
		"check-receiver":        s.CheckReceiver,
		"check-return":          s.CheckReturn,
		"check-type-param":      s.CheckTypeParam,
		"ignore-chan-recv-ok":   s.IgnoreChanRecvOk,
		"ignore-decls":          s.IgnoreDecls,
		"ignore-map-index-ok":   s.IgnoreMapIndexOk,
		"ignore-names":          s.IgnoreNames,
		"ignore-type-assert-ok": s.IgnoreTypeAssertOk,
		"max-distance":          s.MaxDistance,
		"min-name-length":       s.MinNameLength,
	}
}

var _ types.SettingsConverter = VarnamelenSettings{}

// WhitespaceSettings is generated from golangci-lint's JSON Schema.
type WhitespaceSettings struct {
	MultiFunc bool `yaml:"multi-func"`
	MultiIf   bool `yaml:"multi-if"`
}

func (s WhitespaceSettings) ToMap() map[string]any {
	return map[string]any{
		"multi-func": s.MultiFunc,
		"multi-if":   s.MultiIf,
	}
}

var _ types.SettingsConverter = WhitespaceSettings{}

// WrapcheckSettings is generated from golangci-lint's JSON Schema.
type WrapcheckSettings struct {
	ExtraIgnoreSigs        []string `yaml:"extra-ignore-sigs"`
	IgnoreInterfaceRegexps []string `yaml:"ignore-interface-regexps"`
	IgnorePackageGlobs     []string `yaml:"ignore-package-globs"`
	IgnoreSigRegexps       []string `yaml:"ignore-sig-regexps"`
	IgnoreSigs             []string `yaml:"ignore-sigs"`
	ReportInternalErrors   bool     `yaml:"report-internal-errors"`
}

func (s WrapcheckSettings) ToMap() map[string]any {
	return map[string]any{
		"extra-ignore-sigs":        s.ExtraIgnoreSigs,
		"ignore-interface-regexps": s.IgnoreInterfaceRegexps,
		"ignore-package-globs":     s.IgnorePackageGlobs,
		"ignore-sig-regexps":       s.IgnoreSigRegexps,
		"ignore-sigs":              s.IgnoreSigs,
		"report-internal-errors":   s.ReportInternalErrors,
	}
}

var _ types.SettingsConverter = WrapcheckSettings{}

// WslSettings is generated from golangci-lint's JSON Schema.
type WslSettings struct {
	AllowAssignAndAnything       bool     `yaml:"allow-assign-and-anything"`
	AllowAssignAndCall           bool     `yaml:"allow-assign-and-call"`
	AllowCuddleDeclarations      bool     `yaml:"allow-cuddle-declarations"`
	AllowCuddleUsedInBlock       bool     `yaml:"allow-cuddle-used-in-block"`
	AllowCuddleWithCalls         []string `yaml:"allow-cuddle-with-calls"`
	AllowCuddleWithRhs           []string `yaml:"allow-cuddle-with-rhs"`
	AllowMultilineAssign         bool     `yaml:"allow-multiline-assign"`
	AllowSeparatedLeadingComment bool     `yaml:"allow-separated-leading-comment"`
	AllowTrailingComment         bool     `yaml:"allow-trailing-comment"`
	ErrorVariableNames           []string `yaml:"error-variable-names"`
	ForceCaseTrailingWhitespace  int      `yaml:"force-case-trailing-whitespace"`
	ForceErrCuddling             bool     `yaml:"force-err-cuddling"`
	ForceShortDeclCuddling       bool     `yaml:"force-short-decl-cuddling"`
	StrictAppend                 bool     `yaml:"strict-append"`
}

func (s WslSettings) ToMap() map[string]any {
	return map[string]any{
		"allow-assign-and-anything":       s.AllowAssignAndAnything,
		"allow-assign-and-call":           s.AllowAssignAndCall,
		"allow-cuddle-declarations":       s.AllowCuddleDeclarations,
		"allow-cuddle-used-in-block":      s.AllowCuddleUsedInBlock,
		"allow-cuddle-with-calls":         s.AllowCuddleWithCalls,
		"allow-cuddle-with-rhs":           s.AllowCuddleWithRhs,
		"allow-multiline-assign":          s.AllowMultilineAssign,
		"allow-separated-leading-comment": s.AllowSeparatedLeadingComment,
		"allow-trailing-comment":          s.AllowTrailingComment,
		"error-variable-names":            s.ErrorVariableNames,
		"force-case-trailing-whitespace":  s.ForceCaseTrailingWhitespace,
		"force-err-cuddling":              s.ForceErrCuddling,
		"force-short-decl-cuddling":       s.ForceShortDeclCuddling,
		"strict-append":                   s.StrictAppend,
	}
}

var _ types.SettingsConverter = WslSettings{}

// WslV5Settings is generated from golangci-lint's JSON Schema.
type WslV5Settings struct {
	AllowFirstInBlock   bool  `yaml:"allow-first-in-block"`
	AllowWholeBlock     bool  `yaml:"allow-whole-block"`
	BranchMaxLines      int   `yaml:"branch-max-lines"`
	CaseMaxLines        int   `yaml:"case-max-lines"`
	CuddleMaxStatements int   `yaml:"cuddle-max-statements"`
	Default             any   `yaml:"default"`
	Disable             []any `yaml:"disable"`
	Enable              []any `yaml:"enable"`
}

func (s WslV5Settings) ToMap() map[string]any {
	return map[string]any{
		"allow-first-in-block":  s.AllowFirstInBlock,
		"allow-whole-block":     s.AllowWholeBlock,
		"branch-max-lines":      s.BranchMaxLines,
		"case-max-lines":        s.CaseMaxLines,
		"cuddle-max-statements": s.CuddleMaxStatements,
		"default":               s.Default,
		"disable":               s.Disable,
		"enable":                s.Enable,
	}
}

var _ types.SettingsConverter = WslV5Settings{}
