package constants

import "github.com/larsartmann/golangci-lint-auto-configure/pkg/types"

// LinterReasons provides human-readable reasons for each linter recommendation.
var LinterReasons = map[types.LinterName]string{
	// Critical linters
	"loggercheck":  "Checks key value pairs for common logger libraries",
	"gosec":        "Inspects source code for security problems",
	"errcheck":     "Checks for unchecked errors in Go code",
	"staticcheck":  "Advanced static analysis (finds bugs, performance issues)",
	"govet":        "Go vet's suspicious construct checks",
	"errchkjson":   "Checks types passed to json encoding functions",
	"musttag":      "Enforces struct tags for JSON/XML/YAML marshaling",
	"sloglint":     "Ensure consistent code style when using log/slog",
	"nilerr":       "Find code that returns nil even if it checks that error is not nil",
	"noctx":        "Check whether function uses a non-inherited context",
	"paralleltest": "Detects missing usage of t.Parallel() method in Go tests",

	// High value linters
	"wrapcheck":        "Checks that errors returned from external packages are wrapped",
	"errorlint":        "Find code that will cause problems with error wrapping",
	"prealloc":         "Find slice declarations that could potentially be preallocated",
	"unconvert":        "Remove unnecessary type conversions",
	"ineffassign":      "Detect ineffectual assignments",
	"gocyclo":          "Compute cyclomatic complexities",
	"funlen":           "Detect long functions",
	"cyclop":           "Calculate cyclomatic complexities of functions",
	"gocognit":         "Compute cognitive complexities",
	"maintidx":         "Calculate maintenance index",
	"exhaustive":       "Check exhaustiveness of enum switch statements",
	"exhaustruct":      "Check if all struct fields are initialized",
	"goconst":          "Find repeated strings that could be replaced by a constant",
	"misspell":         "Find commonly misspelled English words in comments",
	"revive":           "Fast, configurable, extensible, flexible, and beautiful linter",
	"nolintlint":       "Reports ill-formed or insufficient nolint directives",
	"forcetypeassert":  "Forces type assertions to be safe",
	"gocritic":         "Provides diagnostics for bugs, performance and style issues",
	"unused":           "Checks Go code for unused constants, variables, functions and types",
	"bodyclose":        "Checks whether HTTP response body is closed successfully",
	"contextcheck":     "Check whether the function uses a non-inherited context",
	"dupl":             "Detects duplicate fragments of code",
	"durationcheck":    "Check for two durations multiplied together",
	"errname":          "Checks that sentinel errors are prefixed with Err and error types with Error",
	"gochecknoglobals": "Check that no global variables exist",
	"gochecknoinits":   "Checks that no init functions are present in Go code",
	"gosmopolitan":     "Report i18n/l10n anti-patterns in Go codebase",
	"interfacebloat":   "Checks the number of methods inside an interface",
	"nestif":           "Reports deeply nested if statements",
	"nilnil":           "Checks that there is no simultaneous return of nil error and invalid value",
	"nakedret":         "Checks that functions with naked returns are not too long",
	"predeclared":      "Find code that shadows predeclared identifiers",
	"reassign":         "Checks that package variables are not reassigned",
	"rowserrcheck":     "Checks whether Rows.Err of rows is checked successfully",
	"spancheck":        "Checks for mistakes with OpenTelemetry/Census spans",
	"sqlclosecheck":    "Checks that sql.Rows, sql.Stmt, sqlx.NamedStmt, pgx.Query are closed",
	"testifylint":      "Checks usage of github.com/stretchr/testify",
	"thelper":          "Detects test helpers which do not start with t.Helper()",
	"unparam":          "Reports unused function parameters",
	"wastedassign":     "Finds wasted assignment statements",
	"copyloopvar":      "Detects places where loop variables are copied",
	"ginkgolinter":     "Enforces standards of using ginkgo and gomega",
	"gochecksumtype":   "Run exhaustiveness checks on Go sum types",
	"intrange":         "Finds places where for loops could use integer range",
	"mirror":           "Reports wrong mirror patterns of bytes/strings usage",
	"perfsprint":       "Checks that fmt.Sprintf can be replaced with faster alternative",
	"protogetter":      "Reports direct reads from proto message fields when getters should be used",
	"usetesting":       "Reports uses of functions with replacement inside testing package",
	"recvcheck":        "Checks for receiver type consistency",
	"nilnesserr":       "Reports constructs that check err != nil but return different nil value error",

	// Medium value linters
	"dupword":                   "Checks for duplicate words in the source code",
	"godot":                     "Check if comments end in a period",
	"godox":                     "Check for comments that begin with certain prefixes (TODO, FIXME, etc.)",
	"goheader":                  "Checks that file headers conform to rules",
	"gofmt":                     "Check whether code was gofmt-ed",
	"gci":                       "Check that import order and formatting is correct",
	"varnamelen":                "Check that the length of variable names follows some rules",
	"whitespace":                "Detection of leading and trailing whitespace",
	"wsl_v5":                    "Enforces empty line separation between statements for better readability",
	"grouper":                   "Analyze expression groups",
	"dogsled":                   "Checks assignments with too many identifiers",
	"makezero":                  "Finds slice declarations with non-zero initial lengths",
	"exportloopref":             "Checks for pointers to enclosing loop variables",
	"asciicheck":                "Checks that code identifiers have no non-ASCII symbols",
	"bidichk":                   "Checks for dangerous unicode character sequences",
	"containedctx":              "Detects struct contained context.Context field",
	"decorder":                  "Check declaration order and count of types, constants, variables and functions",
	"depguard":                  "Checks if package imports are in list of acceptable packages",
	"forbidigo":                 "Forbids identifiers",
	"godoclint":                 "Checks Golang's documentation practice (godoc)",
	"gomoddirectives":           "Manage the use of replace, retract, and excludes directives in go.mod",
	"gomodguard":                "Allow and blocklist linter for direct Go module dependencies",
	"ireturn":                   "Accept Interfaces, Return Concrete Types",
	"lll":                       "Reports long lines",
	"mnd":                       "Detects magic numbers",
	"nlreturn":                  "Checks for new line before return and branch statements",
	"nonamedreturns":            "Reports all named returns",
	"promlinter":                "Check Prometheus metrics naming via promlint",
	"tagliatelle":               "Checks the struct tags",
	"testpackage":               "Linter that makes you use separate _test package",
	"tparallel":                 "Detects inappropriate usage of t.Parallel()",
	"unqueryvet":                "Detects SELECT * in SQL queries preventing performance issues",
	"usestdlibvars":             "Detects possibility to use variables/constants from Go standard library",
	"asasalint":                 "Check for pass []any as any in variadic func",
	"canonicalheader":           "Checks whether net/http.Header uses canonical header",
	"err113":                    "Check errors handling expressions",
	"exptostd":                  "Detects functions from golang.org/x/exp/ that can be replaced by std functions",
	"fatcontext":                "Detects nested contexts in loops and function literals",
	"gocheckcompilerdirectives": "Checks that go compiler directive comments are valid",
	"goprintffuncname":          "Checks that printf-like functions are named with f at the end",
	"iface":                     "Detect incorrect use of interfaces, helping avoid interface pollution",
	"imports":                   "Enforces consistent import aliases (requires alias configuration)",
	"inamedparam":               "Reports interfaces with unnamed method parameters",
	"iotamixing":                "Checks if iotas are used in const blocks with other non-iota declarations",
	"modernize":                 "Suggests simplifications using modern Go language and library features",
	"noinlineerr":               "Disallows inline error handling",
	"nosprintfhostport":         "Checks for misuse of Sprintf to construct host with port in URL",
	"tagalign":                  "Check that struct tags are well aligned",
	"testableexamples":          "Checks if examples are testable (have expected output)",

	// Optional linters (not explicitly listed, will use default message)
	"arangolint":               "Opinionated best practices for arangodb client",
	"zerologlint":              "Detects wrong usage of zerolog that forgets to dispatch with Send or Msg",
	"embeddedstructfieldcheck": "Embedded types should be at top of field list with empty line separation",
	"imports":                  "Checks that import aliases follow expected patterns",
}
